remove existing run directory option
snakemake/snakemake-wrappers pull request #1297
Opened 2023-04-27 11:31 UTC by christopher-schroeder

### Description
When strelka reruns it doesn't like if the run directory exists. Add an option to delete it before.

### QC

* [x] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

2023-04-27 11:39 UTC, fgvieira commented
Wouldn't it be better to output to a temp folder and then copy relevant results to their final destination?
For example, like it was done for [STAR](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/star/align/wrapper.py).

2023-04-27 11:45 UTC, christopher-schroeder commented
> Wouldn't it be better to output to a temp folder and then copy relevant results to their final destination? For example, like it was done for [STAR](https://github.com/snakemake/snakemake-wrappers/blob/master/bio/star/align/wrapper.py).

Yes, ok - why not.

2023-04-27 13:15 UTC, fgvieira commented on bio/strelka/germline/test/Snakefile
> +        variants="strelka/{sample}.vcf.gz"
Maybe add explicit names, in case in the future someone wants to implement automatic conversion to other formats (e.g. `bcf`).
```suggestion
        vcf="strelka/{sample}.vcf.gz"
        tbi="strelka/{sample}.vcf.gz.tbi"
```

2023-04-27 18:10 UTC, christopher-schroeder commented on bio/strelka/germline/test/Snakefile
> +        variants="strelka/{sample}.vcf.gz"
I thought about that but wouldn't it be better to call it variants and detect the ending of the filename to automatically convert?

2023-04-28 14:14 UTC, fgvieira commented on bio/strelka/germline/test/Snakefile
> +        variants="strelka/{sample}.vcf.gz"
I (personally) find it easier (and more flexible) to check the format by the name of the output, rather than the actual extension of the file.
@johanneskoester what do you think?

2023-04-28 17:47 UTC, christopher-schroeder commented on bio/strelka/germline/test/Snakefile
> +        variants="strelka/{sample}.vcf.gz"
But this is the normal behaviour of most tools. An example

bcftools view -o test.bcf
bcftools view -o test.vcf
bcftools view -o test.vcf.gz

I very must prefer this over the potential

bcftools view -obcf test.bcf
bcftools view -ovcf test.vcf
bcftools view -ovcfgz test.vcf.gz

2023-05-04 14:56 UTC, johanneskoester commented on bio/strelka/germline/test/Snakefile
> +        variants="strelka/{sample}.vcf.gz"
I agree with @christopher-schroeder , the wrapper should react on the extension, just like we do it with other wrappers as well.

2023-05-04 15:00 UTC, johanneskoester requested changes

2023-05-04 19:43 UTC, christopher-schroeder commented on bio/strelka/germline/test/Snakefile
> +        variants="strelka/{sample}.vcf.gz"
yes, the wrapper is not done yet

2023-05-12 12:10 UTC, johanneskoester commented on bio/strelka/germline/test/Snakefile
> +        variants="strelka/{sample}.vcf.gz"
I unresolved this just so that I don't forget the request until it is done.

2023-06-12 10:25 UTC, johanneskoester approved these changes

2023-06-12 10:25 UTC, merged