feat: added bbtool gneric: One wrapper to un them all!
snakemake/snakemake-wrappers pull request #1322
Opened 2023-05-02 13:50 UTC by SilasK

### Description

I add a generic bbtool wrapper. 
It is based on #2 

BBtools hase many bash shcripts. This wrapper should allow to run them all. 

### QC

* [ ] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

2023-05-02 14:03 UTC, SilasK commented on bio/bbtools/generic/wrapper.py
> +logging.basicConfig(
That's my way to enshure that all errors in the wrapper are written to the log file

2023-05-02 14:03 UTC, SilasK commented on bio/bbtools/generic/wrapper.py
> +## helper functions they should go in snakemake_wrapper_utils
helper functions they should go in snakemake_wrapper_utils

2023-05-02 14:05 UTC, SilasK commented on bio/bbtools/generic/wrapper.py
> +logging.basicConfig(
#885

2023-05-03 14:39 UTC, SilasK commented
Can I ask @fgvieira  and or @dlaehnemann for a review. 

@fgvieira You did the other bbtools snakemake wrappers, isn't it?

2023-05-03 14:39 UTC, SilasK commented on bio/bbtools/generic/wrapper.py
> +## helper functions they should go in snakemake_wrapper_utils
@dlaehnemann Do I need to do this first?

2023-05-04 07:08 UTC, fgvieira commented on bio/bbtools/generic/meta.yaml
> +  - define_threads: By default the the threads argument of snakemake is passed to the bbtool. For bbtools that do not support this argument, set this to False.
Instead of this `param`, what if there was a list of all the BBduk tools that support threads in the wrapper?

2023-05-04 07:08 UTC, fgvieira commented on bio/bbtools/generic/meta.yaml
> +  - other: All other parameters are passed to the bbtool as key=value pairs
It seems this `param` is not used.

2023-05-04 07:13 UTC, fgvieira commented
Nice PR! Can you also add tests for the other rules on the `test/Snakefile`?

And maybe even add the tests from the other `bbduk` wrappers (`bbmap`, `tadpole`, and `loglog`) since, if this wrapper works with all, I'd even say to delete the other wrappers and have this one as the single wrapper for `bbduk`.

2023-05-14 15:32 UTC, fgvieira commented on bio/bbtools/generic/environment.yaml
> +  - python =3.11
Is python really necessary?

2023-05-15 14:16 UTC, fgvieira commented on bio/bbtools/generic/environment.yaml
> +  - python =3.11
I tested the other wrappers (and made #1366), and they seem to run fine without it.

2023-06-13 07:46 UTC, johanneskoester commented on bio/bbtools/generic/environment.yaml
> +  - python =3.11
Yes, if there is no python in the env, Snakemake uses the python from its main process.

2023-06-13 07:48 UTC, johanneskoester requested changes
I also think the other bbtool wrappers should be deleted in order to avoid duplication. One should probably just call the wrapper bbtools, without the "generic" then.

2023-06-27 11:39 UTC, fgvieira commented
And all add tests for other bbtool tools, e.g. `clumpify`.

2023-10-10 13:56 UTC, SilasK commented on bio/bbtools/generic/wrapper.py
> +## helper functions they should go in snakemake_wrapper_utils
Finally now as this will be the only wrapper that uses this

2023-10-10 15:32 UTC, SilasK reviewed
I moved them

2023-10-11 07:56 UTC, SilasK reviewed
I moved the wrapper to the base dir `bio/bbtools` and removed the others. I combined all the tests

2023-10-11 09:38 UTC, fgvieira commented on bio/bbtools/environment.yaml
> +  - snakemake-wrapper-utils =0.5
```suggestion
  - snakemake-wrapper-utils =0.6.2
```

2023-10-11 09:39 UTC, fgvieira commented on bio/bbtools/meta.yaml
> +  This wrapper allows to run any of the bbtools. The command is defined by the 'command' parameter, which required.
```suggestion
  This wrapper allows to run any of the bbtools. The command is defined by the 'command' parameter, which is required.
```

2023-10-11 09:41 UTC, fgvieira commented on bio/bbtools/meta.yaml
> +url: https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide
```suggestion
url: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
```

2023-10-11 09:42 UTC, fgvieira commented on bio/bbtools/meta.yaml
> +    - The wrapper cannot run bbwarap with paired + singleton files. But this is a rare use case.
What is the `bbwarap` tool? I could not find it on the documentation.

2023-10-11 09:45 UTC, fgvieira commented
Left some minor comments but, otherwise, great work!

2023-10-11 12:30 UTC, SilasK commented on bio/bbtools/meta.yaml
> +    - The wrapper cannot run bbwarap with paired + singleton files. But this is a rare use case.
bbwrap can process single + paired end reads, which uses some special input format for in1, in2.

2023-10-11 12:31 UTC, SilasK commented
@fgvieira  Do we need to wait for @johanneskoester  or can you accept the PR.

There will be probably some edge cases in the future. but I think it's quite neat for now.

2023-10-18 07:19 UTC, fgvieira commented on bio/bbtools/test/Snakefile
> +        "logs/index_genome/{sample}.log",
```suggestion
        "logs/index/genome.log",
```

2023-10-24 11:30 UTC, SilasK commented
Cool all checks have passed!

2023-10-24 11:30 UTC, SilasK commented
I think @johanneskoester You need to approve your requested changes

2023-10-25 17:29 UTC, fgvieira commented on bio/bbtools/environment.yaml
> +  - snakemake-wrapper-utils =0.5
Any reason for not using the latest `snakemake_wrapper_utils` version?

2023-11-08 08:04 UTC, fgvieira commented
It seems there is an issue with the test files.

2023-11-08 21:41 UTC, SilasK commented
It worked before 😠 .
It seems a problem with, writing and reading to the index.


BBmap stores index files in `ref/{buildnr}` it allows to change the build number but not really to change the path.
One can ignore the path and set different build numbers if needed. 
But I now set the index directory as an output, which makes things more explicit.

But now, it doesn't really correspond with the wrapper's guideline that input and output can be freely set.

I hope you grant this exception.

2023-11-08 21:51 UTC, SilasK commented
It is passing the checks now @fgvieira Thank you for your patience..

2023-11-09 07:45 UTC, fgvieira commented on bio/bbtools/test/Snakefile
> +        flag=temp(directory("ref/genome/1"))
Should it be a flag, or can it be a `multiext`?

2023-11-09 08:38 UTC, fgvieira commented on bio/bbtools/test/Snakefile
> +        flag=temp(directory("ref/genome/1"))
Just made a quick test, and it seems the `bbmap` index is a variable number of output files (with variable names). Isn't that so?

2023-11-09 10:33 UTC, dlaehnemann commented
> It worked before 😠 . It seems a problem with, writing and reading to the index.
> 
> BBmap stores index files in `ref/{buildnr}` it allows to change the build number but not really to change the path. One can ignore the path and set different build numbers if needed. But I now set the index directory as an output, which makes things more explicit.
> 
> But now, it doesn't really correspond with the wrapper's guideline that input and output can be freely set.
> 
> I hope you grant this exception.

I think you can actually give it an alternative path using the `path=/another/location/` command line argument, which would then be the way to go here. See point `8.` for the index creation here:
https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/bbmap-guide/

2023-11-09 10:51 UTC, SilasK commented
so bbmap index, creates files in `ref/genome/{build_nr}` and `ref/index/{buildnr}`
with `path=path/to /folder` we can give a folder where the ref folder is placed. But, it doesn't correspond to the goal of freely setting an output path.

2023-11-09 10:58 UTC, dlaehnemann commented
But it seems like you are already trying things along those lines... :D

2023-11-09 11:07 UTC, SilasK commented
Thank you for the suggestion. It should work now.

2023-11-09 11:07 UTC, fgvieira commented
Can you bump the `snakemake-wrappers` version?

2023-11-09 12:25 UTC, dlaehnemann commented
> Thank you for the suggestion. It should work now.

And it was easier than I thought. Cool!

2023-11-09 12:50 UTC, SilasK commented
version updated

2023-11-09 14:09 UTC, SilasK commented
But apparently, bbmap's jave doesn't understand the `-Djava.io.tmpdir=/tmp` 

Should I deowngread the snakemake_wrapper_utils

2023-11-09 14:15 UTC, fgvieira commented
Damn... :disappointed:
Not ideal, but I guess we can pin `snakemake-wrapper-utils` to version `0.5.3` until `bbtools` supports it.
@dlaehnemann @johanneskoester What do you think?

2023-11-09 14:48 UTC, dlaehnemann commented
Arrgh, that's ugly. None of the BBTools shell scripts passes anything except for the memory specification on to Java. I guess the thorough (but laborious) fix would be to switch to the actual java script syntax, namely this:
```


 Maybe we should add an argument to `get_java_opts(adjust_tmpdir=True)`, which you can then unset in your `get_java_opts()` call.

2023-11-09 15:04 UTC, dlaehnemann commented
I think you could parse the file `ToolDescriptions.txt` from the folder `bbmap/docs/` of the [downloadable `BBTools` source code from sourceforge](https://sourceforge.net/projects/bbmap/files/latest/download) to get a mapping from shell script to java tool. But then I also just saw that they seem to pass some hard-coded default values to some tools. So switching from the shell scripts will loose default parameter settings... :exploding_head:

2023-11-09 15:08 UTC, dlaehnemann commented
Hmm, but if we look at the actual java command that is executed, the option is still in there. So it is simply the sanity checking of BBTools that is off here. Maybe passing `-da` will turn this off? But then, this might turn other useful checks off...

2023-11-09 15:33 UTC, dlaehnemann commented
Mhmmm, no. It seems like `-da` will not turn off the failure we get...

2023-11-09 16:05 UTC, SilasK commented
Alternatively, we could re-implement the get_java_opts inside the wrapper?

2023-11-09 16:23 UTC, dlaehnemann commented
Or remove the respective part from the resulting `java_opts` string via a regex. :see_no_evil:

2023-11-09 16:29 UTC, dlaehnemann commented
Or maybe we can change the `get_java_opts` to instead set all of the general option in `os.environ["JDK_JAVA_OPTIONS"] = "-Djava.io.tmpdir={}"`. This sounds like this should then automatically use those options in any following `java` call:
https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#using-the-jdk_java_options-launcher-environment-variable

Why are Java tools always such a headache... :disappointed:

2023-11-09 21:19 UTC, SilasK commented
Change impelemented.

2023-11-09 21:43 UTC, dlaehnemann commented
Nice. But yes, (not) knowing Java and all, I am also a bit concerned this might not work as expected. And have no idea how to easily test this.

Maybe one could try to locally (and manually) run the tests on this pull request and on some other wrapper(s) that use the `get_java_opts()` function, while having manually modified the respective conda environments' `snakemake-wrapper-utils` to include the change...?!

2023-11-10 16:57 UTC, dlaehnemann commented
I think you might have to split the `'--default-resources mem_mb=200'` into two separate arguments, so `'--default-resources', 'mem_mb=200'`.

2023-11-13 08:37 UTC, SilasK commented
@dlaehnemann  To follow up on 
> But this is something that the user might want to set via snakemake command-line options or via the `resources: tempdir=` directive in a rule using the wrapper, so it would then be good if the wrapper did pass this on to the actual execution of the tool.
https://github.com/snakemake/snakemake-wrapper-utils/pull/37#issuecomment-1805909767

I don't think bbmap uses tempdirs a lot. But I found that one command can use it.

> The location of temp files can be specified with the “tmpdir” flag; it defaults to the environment variable $TMPDIR, which on Genepool points to local disk when available. Temp files will be cleaned up once BBNorm finishes.

`$TMPDIR` will already be set by snakemake using the `resources.tempdir` isn't it. So I would say the specification of tempdir should be ok, fo rbbtools.

2023-11-13 09:34 UTC, dlaehnemann reviewed
It seems like I had some comments a while ago, that are still lurking around. I think only the latest one is relevant and will try to resolve all the others. Sorry for the noise.

And many thanks for following up on the `$TMPDIR` question. If `bbtools` don't seem to use it and if they do, to respect the environment variable, then I think you are right -- we can ignore this for the wrapper...

2023-11-13 09:34 UTC, dlaehnemann commented on bio/bbtools/wrapper.py
> +    return " -Xmx{}M".format(round(mem_mb * (1.0 - java_mem_overhead_factor)))
Sorry to have one more suggestion here: wouldn't it be a bit more future-proof to simply use the snakemake-wrapper-utils `get_java_opts` and simply extract only the `-Xmx` option with a regex? That way, we don't reimplement it here and if something gets fixed in the utils function, we also benefit here.

2023-11-13 12:51 UTC, SilasK commented
I now extract the mem using a regex.

I also made a major update to the Snakefile test. It now represents a good usage of the wrapper and the bbtools functions. 
e.g. previously all parameters were input as a comma-separated string. 
With the same rules, it works for paired or single-end reads.

What do you think of my updated workflow?

2023-11-13 12:56 UTC, fgvieira commented
I think it looks good but, since it will introduce breaking changes, not sure if @johanneskoester want to take a look first.

2023-11-13 13:33 UTC, dlaehnemann approved these changes
This generally looks good to me. But I haven't looked at all the wrapper.py code in detail -- @johanneskoester has requested changes anyway, and will thus have to have another look. I'll ping him...

2023-11-13 16:10 UTC, johanneskoester approved these changes

2023-11-13 21:25 UTC, SilasK commented on bio/bbtools/test/Snakefile
> +include: "input_functions.smk"
I had it this way. But then the lining didn't pass.

2023-11-13 21:27 UTC, SilasK commented on bio/bbtools/test/Snakefile
> +        # With build by defualt 1 and path by default the working directory
Maybe it's not clear, The comment explains the workings of path and build. 
But maybe we don't need to bother the users with that.

2023-11-13 21:34 UTC, SilasK commented on bio/bbtools/test/Snakefile
> +        # With build by defualt 1 and path by default the working directory
I adapted the commend and moved it down in the Snakefile as it is less important.

2023-11-13 21:38 UTC, SilasK commented on bio/bbtools/wrapper.py
> +import warnings
imported at the beginning now.

I have a second section of imports after all the logging is set up.
So that errors in imports would also be logged to the log file.

2023-11-13 21:41 UTC, SilasK commented
Now we are almost done!

I had two problems with the linter:

1. It didn't want me to have functions in the main Snakemake, therefore the import. Even if I think it's less ideal.

2. It interpreted a `ktrim="r"` as a path, and didn't accept it. I found a solution, which is less optimal.

2023-11-13 21:42 UTC, SilasK commented
In the wrapper I put the links to other PRs in snakemake that will incorporate these functions. But I guess we should not wait until then to release the next version of this wrapper.

2023-11-14 10:12 UTC, dlaehnemann commented on bio/bbtools/test/Snakefile
> +include: "input_functions.smk"
Ah, I see. That's a bit annoying in this setup. But I guess there's no way around it for now. Maybe add a quick comment above the include, which rule this is for and the function name? Although the file name is rather descriptive already... :D

2023-11-14 10:14 UTC, dlaehnemann commented on bio/bbtools/wrapper.py
> +import warnings
Ah, OK. That makes sense. Maybe add a quick comment at the start, that there is another import block below, at the `start of the wrapper`?

2023-11-14 10:23 UTC, dlaehnemann commented
> Now we are almost done!
Yes, definitely!

> I had two problems with the linter: 
>     1. It didn't want me to have functions in the main Snakemake, therefore the import. Even if I think it's less ideal.
Then I guess we'll leave it as is. Maybe add a comment as suggested, if you think this is useful.
 
>     2. It interpreted a `ktrim="r"` as a path, and didn't accept it. I found a solution, which is less optimal.
Is that under params? Because I would find that weird, and possibly a linter bug. But if it enforces this for input and output, this makes sense. Then, I would suggest simply specifying this as a param. And if that's what you did, did you try something like either of the following, to make it work with the current linter:
```
params:
    ktrim="'r'",
    ktrim="'r' ",
    ktrim="r ",
```

As for the links to PRs, I think it is perfectly fine to simply leave those as TODOs. Maybe make it a bit clearer still, that once these are merged, the respective functions can simply go away and use snakemake internal functionality.

2023-11-14 10:41 UTC, SilasK commented
It looks like a linter bug:
[Code](https://github.com/metagenome-atlas/snakemake-wrappers/blob/37d0bf2dfcfbde20269090c687e4184136033779/bio/bbtools/test/Snakefile#L88C1-L92C19)
[Error](https://github.com/snakemake/snakemake-wrappers/actions/runs/6849925541/job/18623086042)

2023-11-14 14:54 UTC, dlaehnemann commented
Ah, thanks for the pointers to the linter. Regarding the (input) function, you could indeed make this an inline lambda expression like this:

```
rule loglog:
    input:
        expand(
            "reads/raw/{{sample}}_{fraction}.fastq.gz",
            fraction=lambda wc: ["R1", "R2"] if config.get("reads_are_paired", True) else ["se"]
        ),
```

It has the advantage of being right there in the input of the rule. It has the disadvantage of being slightly less readable than the actual function with newlines. And you'll have to repeat that code wherever you provide such a read `fraction` specification. It seems like there's no perfect solution with the current linter.

And from what I understand about the `ktrim="r"`, this recognizes that `r` is a prefix of the input/output path, which starts with `reads/...`. That's a very short prefix, but it is correct. The linter could probably be amended to ignore such single letter cases or make it more of a suggestion, then a must (not sure if that exists, though). And I think you should get around this by including some random whitespace at the end, so:
`ktrim="r "`
Then, it shouldn't be a prefix any more...

2023-11-14 18:04 UTC, SilasK commented
The whitespace fixed the linter.

I find the lambda version less clear.

2023-11-14 19:23 UTC, dlaehnemann commented
Agreed, I'll merge! :tada:

2023-11-14 19:23 UTC, merged

2023-11-14 20:24 UTC, SilasK commented
Thank you very much for your review and your suggestions!

2023-11-14 20:55 UTC, dlaehnemann commented
Thanks for keeping at it! Getting things right for reproducible and reusable data analyses can be exhausting, especially when you're battling with multiple levels of the workflow / analysis stack and several workflows at the same time.

So take a moment and celebrate! :rocket:

2023-11-14 20:57 UTC, fgvieira commented
Nice work!!