Gridss (Draft)
snakemake/snakemake-wrappers pull request #156
Opened 2020-08-17 13:44 UTC by christopher-schroeder

In Progress, please do not review yet

2020-08-20 19:56 UTC, jafors requested changes
That's a lot of wrappers and checks. Thanks!

Some first thoughts below!

2020-08-20 19:56 UTC, jafors commented on bio/gridss/assemble/wrapper.py
> +        )
I'm not sure if we should use f-strings. Yes, Python 3.6 is old news, but I remember Johannes making a point that we want to be as backwards compatible as possible.

2020-08-20 19:56 UTC, jafors commented on bio/gridss/setupreference/test/Snakefile
> +        "file:/vol/huge/christo/snakemake-wrappers/bio/gridss/setupreference"
This should probably be
```
    wrapper:
        "master/bio/gridss/setupreference"
```
Right?

2020-08-20 19:56 UTC, jafors commented on bio/gridss/call/wrapper.py
> +    "(export JAVA_OPTS='-XX:ActiveProcessorCount=8' & "
Should the Java opts be chooseable as a parameter or is this specific option simply the ideal choice and should stay fixed?

2020-08-21 07:48 UTC, christopher-schroeder commented on bio/gridss/assemble/wrapper.py
> +        )
you are right, I will replace them

2020-08-21 07:56 UTC, christopher-schroeder commented on bio/gridss/call/wrapper.py
> +    "(export JAVA_OPTS='-XX:ActiveProcessorCount=8' & "
Well simply: I don't know. I set this to {threads} but it might be that we have to include a cpu limiter for real data.

2020-08-25 08:31 UTC, jafors approved these changes

2020-08-25 08:32 UTC, merged