feat: Added general log
snakemake/snakemake-wrappers pull request #1775
Opened 2023-08-31 08:13 UTC by fgvieira

### Description

### QC

* [x] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

2023-10-30 19:26 UTC, johanneskoester requested changes

2023-10-30 19:26 UTC, johanneskoester commented on bio/vsearch/test/Snakefile
> +        log="out/cluster_fast/{sample}.log",
What is this additional log supposed to contain, how is it different from the other log below? And why is it not under logfiles?

2023-10-30 19:27 UTC, johanneskoester commented on bio/vsearch/test/Snakefile
> +        log="out/cluster_fast/{sample}.log",
I guess it is only me being uninformed about vsearch, but maybe a clarifying comment should be added.

2023-10-31 07:19 UTC, fgvieira commented on bio/vsearch/test/Snakefile
> +        log="out/cluster_fast/{sample}.log",
`vsearch` allows to specify a log file through the command line (current `output.log`) but, to be consistent with the other wrappers and since that log is optional, I kept the `stdout` log too.

I can move `output.log` to `log.some_name`, e.g.:
```
    log:
        "logs/vsearch/cluster_fast/{sample}.log",
        log="out/cluster_fast/{sample}.log",
```
or, when not specified (since it should be an optional log):
```
    log:
        "logs/vsearch/cluster_fast/{sample}.log",
```

Do you think that would make more sense?

2023-12-14 22:02 UTC, johanneskoester requested changes

2023-12-14 22:02 UTC, johanneskoester commented on bio/vsearch/test/Snakefile
> +use rule vsearch_cluster_fast as vsearch_maskfasta with:
I would not use `use rule` here. People might want to copy paste from this file, and for that every variant of the rule should work standalone.

2023-12-16 11:17 UTC, fgvieira commented
I thought a bit more about the `log` file and, since it is not exactly the same as the `stdout`, it makes sense to support it. However, I think having it as `verbose` might be a bit confusing since it is not clear where that output comes from.
If we leave it an optional output, then it is clear it comes from the `vsearch` command line argument `log` (just like all the other outputs).

2023-12-18 09:58 UTC, johanneskoester commented
Mhm, but it will be lost upon error. log is really the right place for these things. If you don't like verbose, maybe call the two logs `std` and `vsearch`?

2023-12-18 10:58 UTC, fgvieira commented
That is true, the outputs are lost in error.

2023-12-18 19:39 UTC, johanneskoester approved these changes

2023-12-18 19:39 UTC, merged