feat: Gseapy
snakemake/snakemake-wrappers pull request #1822
Opened 2023-09-26 11:55 UTC by tdayris

### Description

This PR adds `gseapy` to the list of available wrappers. I plan to add replot, dotplots, heatmaps, and barplots functions in the future.

### QC

* [X] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

2023-10-04 13:58 UTC, johanneskoester requested changes

2023-10-04 13:58 UTC, johanneskoester commented on bio/gseapy/gsea/test/Snakefile
> +        directory("results_enrichr"),
I think it is preferable to have the individual output files here. Or are they unpredictable/of unknown multiplicity?

2023-10-24 11:05 UTC, tdayris commented on bio/gseapy/gsea/test/Snakefile
> +        directory("results_enrichr"),
In this case, we have both scenarios.

There a three known and predictable files which can be tracked. Depending on user parameters and GSEApy results, there is an unknown number of files named after the original prefix defines by user (parameters), the database defined by user (parameters) and the pathways significantly enriched (tool results).

Downstream analysis is based on that directory architecture. We can reproduce it later.

Let next commit be my attempt at naming as much results as possible.

2023-10-30 19:20 UTC, johanneskoester approved these changes

2023-10-30 19:20 UTC, merged