feat: Methyledackel extract
snakemake/snakemake-wrappers pull request #1823
Opened 2023-09-27 11:40 UTC by tdayris

### Description

This PR adds MethylDackel extract to the list of available wrappers.

### QC

* [X] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

2023-10-04 13:54 UTC, johanneskoester requested changes

2023-10-24 07:34 UTC, tdayris commented on bio/methyldackel/extract/wrapper.py
> +    else:
Turning on report flag, only produces the report output, even though the other flags `CHG` or `CHH` are also turned on:

`$ MethylDackel extract --CHG --CHH --cytosine_report chgchh.fa chgchh_aln.bam && tree` 

```
├── chgchh_aln.bam
├── chgchh_aln.bam.bai
├── chgchh_aln.cytosine_report.txt # <- Only produced report
├── chgchh.fa
└── chgchh.fa.fai
```

On the other side, turning off the report parameter lets the tool create all the other file(s) :

`$ MethylDackel extract --CHG --CHH chgchh.fa chgchh_aln.bam && tree` 

```
├── chgchh_aln.bam
├── chgchh_aln.bam.bai
├── chgchh_aln_CHG.bedGraph # <- CHG
├── chgchh_aln_CHH.bedGraph # <- CHH
├── chgchh_aln_CpG.bedGraph # <- CpG
├── chgchh.fa
└── chgchh.fa.fai

If I allow report alongside with other flags, then the `shell("mv ...")` ends with a non null return-code due to file not found.

I rather let the wrapper fail with a snakemake error on output file not produced.

What do you think about it ?

2023-10-24 07:35 UTC, tdayris commented on bio/methyldackel/extract/wrapper.py
> +        if "--noCpG" not in extra:
This is better indeed. Changes have been made accordingly.

2023-10-26 08:47 UTC, johanneskoester commented on bio/methyldackel/extract/wrapper.py
> +    else:
ok, makes sense!

2023-10-26 08:47 UTC, johanneskoester approved these changes

2023-10-26 08:47 UTC, merged