Added wrapper for mapDamage2
snakemake/snakemake-wrappers pull request #186
Opened 2020-09-18 12:20 UTC by fgvieira

Implementation of the wrapper for mapDamage2.

More info about the program:
https://github.com/ginolhac/mapDamage
https://ginolhac.github.io/mapDamage/

2020-09-24 08:05 UTC, johanneskoester requested changes
Thank you! It was actually not intentional to not have a test with picard markduplicates. Hence, can you add one for the new wrapper here, and probably copy it over to markduplicates as well?

2020-09-24 08:05 UTC, johanneskoester commented on bio/mapdamage2/environment.yaml
> +  - mapdamage2 =2.2.1=pyr40_0
Please just pin to the version, not the build string (build strings are not guaranteed to stay valid forever).
```suggestion
  - mapdamage2 =2.2.1
```

2020-10-12 07:53 UTC, fgvieira commented
@johanneskoester sorry for all the new wrappers on a single PR, but kept making new ones and forgot to make new branches. Will do it next time...

2020-10-22 12:22 UTC, dlaehnemann requested changes
Thanks for this big contribution! This generally looks good, just a number of suggestions and some minor things to fix.

As you already noted, smaller PRs are probably the way to go in the future. Makes it easier and quicker to review, and easier to merge in case of conflicts.

2020-10-22 12:22 UTC, dlaehnemann commented on bio/samtools/calmd/test/Snakefile
> +	ref = "genome.fasta"
Tabs instead of whitespace indentation, should be:
```suggestion
        ref = "genome.fasta"
```

2020-10-22 12:22 UTC, dlaehnemann commented on bio/samtools/calmd/test/Snakefile
> +        bam = "{sample}.bam", # Can be 'sam', 'bam', or 'cram'
Maybe make this a generic input name like `alignment =`? `samtools calmd` should do automatic file type detection and should even throw useful error messages if that doesn't work. And this way, users only have to adjust the extension, and not the input variable key name.

2020-10-22 12:22 UTC, dlaehnemann commented on bio/samtools/sort/wrapper.py
> +    prefix = os.path.splitext(snakemake.output[0])[0]
I would argue that this should always be appended to any specified prefix. As a prefix specified via `params.prefix` will usually be the same for all instances of the rule, this could otherwise lead to multiple instances writing to and reading from the same temporary files, e.g. when bam files with the same name exist in separate subfolders and are handled at the same time. Or maybe, to distinguish between the prefix and where to put temporary sorting files, the `params` parameter could instead be named `tmp_folder` and the path without the extension then used at that location?

2020-10-22 12:22 UTC, dlaehnemann commented on test.py
> +
This is the same two tests twice, or am I missing some subtle difference?

2020-10-22 12:22 UTC, dlaehnemann commented on test.py
> +
As above, it seems like every test appears twice in exactly the same form. Did you intend to edit one variant each?

2020-10-22 13:24 UTC, fgvieira commented on test.py
> +
Even though it is the same wrapper, the tests are for different situations, namely:
`sam` from single-end
`sam` from paired-end
`bam` from single-end
`bam` from paired-end

2020-10-22 13:27 UTC, fgvieira commented on test.py
> +
Again, even though it is a single wrapper, I added several tests for several outputs, namely:
samtools sorted `bam` from single-end
samtools sorted `bam` from paired-end
picard sorted `sam` from single-end
picard sorted `sam` from paired-end
picard sorted `bam` from single-end
picard sorted `bam` from paired-end

2020-10-22 13:42 UTC, fgvieira commented on bio/picard/markduplicateswithmatecigar/wrapper.py
> +
Added JVM memory handling just like in other picard/gatk wrappers

2020-10-22 13:57 UTC, dlaehnemann commented on test.py
> +
Ah, OK. I did miss the subtle difference between `s`am and `b`am, of course. Sorry, my bad!

2020-10-22 14:12 UTC, fgvieira commented on bio/bcftools/sort/meta.yaml
> +description: Sort vcf/bcf file.
Added link to docs on all wrappers, plus some more...

2020-10-22 16:48 UTC, dlaehnemann commented
Cheers for the immediate flurry of activity! You might just be quicker than PR #204! :D

2020-10-22 20:06 UTC, fgvieira commented on bio/samtools/calmd/test/Snakefile
> +        bam = "{sample}.bam", # Can be 'sam', 'bam', or 'cram'
Implemented generic input name and automated output format detection

2020-10-22 20:35 UTC, fgvieira commented on bio/bcftools/sort/test/Snakefile
> +        extras = "-Ob"
What if the user wants to output uncompressed `bcf` for further piping?

2020-10-22 20:55 UTC, fgvieira commented on bio/samtools/sort/wrapper.py
> +    prefix = os.path.splitext(snakemake.output[0])[0]
Fixed issue when specifying prefix

2020-10-23 10:01 UTC, johanneskoester requested changes
Thanks a lot for this huge contribution! However, please remove the bwa sam wrappers. I'd rather have the existing bwa wrappers dynamically react on the chosen extension of the output file.

2020-10-23 10:21 UTC, fgvieira commented on bio/samtools/sort/wrapper.py
> +import os.path as p
Reverted back import changes

2020-10-23 10:31 UTC, fgvieira commented
Not quite sure what you mean by 
> [...] I'd rather have the existing bwa wrappers dynamically react on the chosen extension of the output file.

Current `bwa sampe` and `bwa samse` wrappers have the same output file extension. In fact, they are identical except for the number of input `.fastq` and `.sai` files.

The only thing that the `bwa sam` wrapper I include here does, is to infer which algorithm to use (`sampe` or `samse`) from the number of input `fastq` and `sai` files.

2020-10-23 12:16 UTC, johanneskoester commented
> Not quite sure what you mean by
> 
> > [...] I'd rather have the existing bwa wrappers dynamically react on the chosen extension of the output file.
> 
> Current `bwa sampe` and `bwa samse` wrappers have the same output file extension. In fact, they are identical except for the number of input `.fastq` and `.sai` files.
> 
> The only thing that the `bwa sam` wrapper I include here does, is to infer which algorithm to use (`sampe` or `samse`) from the number of input `fastq` and `sai` files. Just like we have a single `bwa mem` wrapper for both PE and SE, I think it makes sense to also have a single wrapper for `bwa sam`.

Ah, sorry, I misunderstood that. The problem is the name, which somehow suggests dealing with SAM files. Maybe call it `bwa samxe` instead?

2020-10-23 12:43 UTC, fgvieira commented
sounds good...

2020-10-23 15:28 UTC, dlaehnemann commented on bio/bcftools/sort/test/Snakefile
> +        extras = "-Ob"
Not sure if you have seen this suggestion, @fgvieira? Once this is in, I think we can merge the whole PR.

2020-10-23 15:31 UTC, dlaehnemann commented on bio/bcftools/sort/test/Snakefile
> +        extras = "-Ob"
Ah, wait. I now see that it is implemented. Maybe describe the option of using it somewhere? Either in the description of the wrapper, or by including `uncompressed_bcf=false` with an explanatory comment in the example rule?

2020-10-28 08:37 UTC, fgvieira commented on bio/bcftools/sort/test/Snakefile
> +        extras = "-Ob"
I've added the `uncompressed_bcf=false` to the example rule

2020-10-28 10:38 UTC, dlaehnemann commented on bio/bcftools/sort/wrapper.py
> +__copyright__ = "Copyright 2021, Filipe G. Vieira"
Sorry, 2020 is not yet over...
```suggestion
__copyright__ = "Copyright 2020, Filipe G. Vieira"
```

2020-10-28 10:39 UTC, dlaehnemann commented on bio/bwa/samxe/wrapper.py
> +__copyright__ = "Copyright 2021, Filipe G. Vieira"
```suggestion
__copyright__ = "Copyright 2020, Filipe G. Vieira"
```

2020-10-28 10:39 UTC, dlaehnemann commented on bio/mapdamage2/wrapper.py
> +__copyright__ = "Copyright 2021, Filipe G. Vieira"
```suggestion
__copyright__ = "Copyright 2020, Filipe G. Vieira"
```

2020-10-28 10:40 UTC, dlaehnemann commented on bio/samtools/calmd/wrapper.py
> +__copyright__ = "Copyright 2021, Filipe G. Vieira"
```suggestion
__copyright__ = "Copyright 2020, Filipe G. Vieira"
```

2020-10-28 10:44 UTC, dlaehnemann approved these changes

2020-10-28 10:58 UTC, johanneskoester approved these changes

2020-10-28 10:58 UTC, merged

2020-10-28 10:58 UTC, johanneskoester commented
Awesome, thanks a lot!

2020-10-28 12:15 UTC, dlaehnemann commented
Yes, thanks again @fgvieira. Cool additions and improvements to the wrapper collection!