Add wrappers for vg and wgsim
snakemake/snakemake-wrappers pull request #190
Opened 2020-09-22 14:40 UTC by cartoonist

I created the same PR a while ago when the repository was on BitBucket. It was stalled because vg was not on conda at that time. Now, they are on conda. I have updated those wrappers with the latest version of vg and wgsim.

2020-09-24 08:09 UTC, johanneskoester requested changes
Awesome, I am really happy to finally being able to merge this. Just one request about the version in each of the conda envs below.

2020-09-24 08:09 UTC, johanneskoester commented on bio/vg/construct/environment.yaml
> +  - vg >=1.27.0
```suggestion
  - vg ==1.27.0
```
We never know what happens in the future, hence wrappers are usually pinned to an exact version.

2020-09-24 12:46 UTC, cartoonist commented on bio/vg/construct/environment.yaml
> +  - vg >=1.27.0
That makes sense. I pinned `vg` and `wgsim` to the exact version.

2020-10-13 20:51 UTC, cartoonist commented
Just a kind reminder. I applied the requested changes.

2020-10-23 12:17 UTC, johanneskoester approved these changes

2020-10-23 12:17 UTC, merged

2020-10-23 12:18 UTC, johanneskoester commented
Thanks a lot for the reminder!