added pbmm2 index and align commands
snakemake/snakemake-wrappers pull request #193
Opened 2020-09-25 05:34 UTC by williamrowell

pbmm2 is a wrapper for minimap2 supporting native PacBio formats for input and output.  I've added the pbmm2 index and align subcommands.

2020-10-23 12:22 UTC, johanneskoester requested changes
Thanks a lot! Just two minor things.

2020-10-23 12:22 UTC, johanneskoester commented on bio/pbmm2/align/test/Snakefile
> +        sample = "",
Please explain each param with a comment to the right of it.

2020-10-23 12:22 UTC, johanneskoester commented on bio/pbmm2/align/test/Snakefile
> +        reference = "target/{reference}.fasta", # can be either genome index or genome fasta
Please format all items as `key=...` instead of `key = ...`

2020-10-23 12:22 UTC, johanneskoester commented on bio/pbmm2/align/test/Snakefile
> +        reference = "target/{reference}.fasta", # can be either genome index or genome fasta
same for the other wrapper below.

2020-10-27 20:30 UTC, williamrowell commented on bio/pbmm2/align/test/Snakefile
> +        sample = "",
Added comments for clarification.

2020-10-27 20:30 UTC, williamrowell commented on bio/pbmm2/align/test/Snakefile
> +        reference = "target/{reference}.fasta", # can be either genome index or genome fasta
Reformatted both Snakefiles and pushed.  Thank you.

2020-11-30 09:06 UTC, johanneskoester approved these changes

2020-11-30 09:06 UTC, merged