added jellyfish count, dump, histo, and merge subcommands
snakemake/snakemake-wrappers pull request #194
Opened 2020-09-25 05:37 UTC by williamrowell

Added commands for counting of kmers, dumping kmers, producing a kmer histogram, and merging kmer databases.

2020-10-23 12:24 UTC, johanneskoester requested changes
Thanks a lot. Just the formatting, see below.

2020-10-23 12:24 UTC, johanneskoester commented on bio/jellyfish/merge/test/Snakefile
> +rule jellyfish_merge:
Please format all test Snakefiles with [Snakefmt](https://github.com/snakemake/snakefmt).

2020-10-27 20:30 UTC, williamrowell commented on bio/jellyfish/merge/test/Snakefile
> +rule jellyfish_merge:
reformatted and pushed

2020-11-30 09:08 UTC, johanneskoester submitted a review, later dismissed
Sorry for the delay, I just discovered that I missed one other thing: you also need to add test cases for the wrappers. Otherwise, we cannot see if they suddenly break in the future.

2021-05-27 09:36 UTC, dlaehnemann commented
@williamrowell Thanks again for this contribution. We are currently going through all the PRs on `snakemake-wrappers` and I was wondering if you still have plans to add tests to this PR and your other open PRs? Or won't you find the time and we should see if we can amend and merge them?

2021-05-27 15:53 UTC, williamrowell commented
Thanks, and sorry for leaving this unfinished.  Unfortunately I won't have time for at least a few more weeks, so if you don't mind, feel free to amend and merge.  Same goes for any of my open PRs.

2021-05-27 16:18 UTC, dlaehnemann commented
Thanks for the update!

2021-12-05 04:27 UTC, williamrowell commented
I've updated this and added a test case.  It's ready for review.

2021-12-06 17:33 UTC, dlaehnemann approved these changes
Thanks a bunch for updating this with tests!

I added a suggestion to unpin the the patch version in the environment definition. But if you have a good reason to pin it to that exact version, that's also OK.

2021-12-06 17:33 UTC, dlaehnemann commented on bio/jellyfish/count/environment.yaml
> +  - kmer-jellyfish==2.3.0
I there a particular reason for this to be pinned to `2.3.0`? Otherwise I'd opt for:
```suggestion
  - kmer-jellyfish==2.3
```

That way, bug fixes and especially stuff like security patches will automatically be used whenever available.

2021-12-06 17:33 UTC, dlaehnemann commented on bio/jellyfish/dump/environment.yaml
> +  - kmer-jellyfish==2.3.0
As above, I'd suggest:
```suggestion
  - kmer-jellyfish==2.3
```

2021-12-06 17:33 UTC, dlaehnemann commented on bio/jellyfish/histo/environment.yaml
> +  - kmer-jellyfish==2.3.0
As above, I'd suggest:
```suggestion
  - kmer-jellyfish==2.3
```

2021-12-06 17:33 UTC, dlaehnemann commented on bio/jellyfish/merge/environment.yaml
> +  - kmer-jellyfish==2.3.0
As above, I'd suggest:
```suggestion
  - kmer-jellyfish==2.3
```

2021-12-06 18:18 UTC, merged

2021-12-06 18:19 UTC, dlaehnemann commented
Thanks again for revisiting this and finishing up the PR! :tada:

2021-12-06 18:21 UTC, williamrowell commented
Sorry for the delay.  Thanks for merging.  I updated and added tests to all but 2 of my open PRs.  The last two I need to think a little more carefully about how to construct test cases.