added bgzip compression
snakemake/snakemake-wrappers pull request #195
Opened 2020-09-25 05:37 UTC by williamrowell

Added wrapper for using bgzip to compress a file.

2020-10-05 14:04 UTC, jafors requested changes
Thanks for the effort in all your PRs. I'll start with this one, solid work, just one thing below in the `params`.

2020-10-05 14:04 UTC, jafors commented on bio/bgzip/test/Snakefile
> +        extra: ""  # optional
```suggestion
    params:
        extra=""  # optional
```

2020-10-05 14:28 UTC, jafors commented
Oh, and I just saw that you are missing testcases for most of your wrappers. Please remember to commit the test data and the updated test.py when you provide a new wrapper.

2020-10-09 19:55 UTC, williamrowell commented
Just wanted to drop a note that I'm not ignoring you, just busy at the moment.  Thanks for following up.  In some cases (like this one, for instance), I should be able to easily add tests, but others will likely take more time.

2020-10-27 20:37 UTC, williamrowell commented on bio/bgzip/test/Snakefile
> +        extra: ""  # optional
Fixed this error and reformatted Snakefile with snakefmt.

2020-10-27 20:38 UTC, williamrowell commented
Sorry this took a while to get back to, and thanks for your patience.  I made the change you suggested, and added a test case to test.py. This is the first time I've added a test case.  I will work on some of the other PRs as well.

2020-11-02 10:10 UTC, jafors approved these changes

2020-11-02 10:34 UTC, jafors requested changes
Hi, thanks for the additional work! One thing I just saw - could you add a smaller testcase? 14MB seems a bit to large for a test.vcf - actually, one or two records would be sufficient.

2020-11-02 16:23 UTC, williamrowell commented
Sorry, I had originally grabbed the example VCF from the tabix wrapper, not realizing it was 14MB.  I just replaced the test case with a minimal with a handful of entries.

2020-11-03 07:08 UTC, jafors requested changes
Thanks! Sorry to bother you further, but I already proposed an additional improvement which we should think about. Hopefully, this should not be too much of a hassle.

2020-11-03 07:08 UTC, jafors commented on bio/bgzip/wrapper.py
> +extra = snakemake.params.get("extra", "")
The wrapper should probably do some parameter checks in `extra` - if e.g. someone wants to use `-c|--stdout`, there needs to be a `> {snakemake.output}` appended to the end of the shell call.
You could do this with a new variable like `output` which contains `> {snakemake.output}` if  `-c|--stdout` in `extra` and an empty string otherwise.

2021-06-24 19:57 UTC, johanneskoester commented on bio/bgzip/wrapper.py
> +extra = snakemake.params.get("extra", "")
I think that should even be the only behavior. This makes the choice of the output file completely free.

2021-12-05 04:27 UTC, williamrowell commented
I've updated, changed the default behavior to `bgzip -c`, and added a test case.  It's ready for review.

2022-01-26 14:32 UTC, johanneskoester approved these changes

2022-01-26 14:33 UTC, merged