added wrapper for bcftools stats
snakemake/snakemake-wrappers pull request #201
Opened 2020-09-25 06:12 UTC by williamrowell

Added bcftools stats subcommand wrapper.

2020-11-30 09:59 UTC, johanneskoester reviewed
Thanks a lot! Please add a test case with small test data and a corresponding function in `test.py`.

2020-11-30 09:59 UTC, johanneskoester requested changes
See above.

2021-12-05 04:25 UTC, williamrowell commented
I've updated this and added a test case.  It's ready for review.

2022-01-26 14:38 UTC, johanneskoester approved these changes

2022-01-26 14:42 UTC, merged