added wrapper for seqtk seq subcommand
snakemake/snakemake-wrappers pull request #202
Opened 2020-09-25 06:16 UTC by williamrowell

seqtk seq can be used to easily convert or reformat fasta/q files.

2020-11-30 10:25 UTC, johanneskoester requested changes
Please format the `Snakefile` with snakefmt, and add a test case to `test.py`.

2020-11-30 10:25 UTC, johanneskoester commented
And thanks a lot!

2021-12-05 04:25 UTC, williamrowell commented
I've updated this and added a test case.  It's ready for review.

2022-01-26 14:40 UTC, johanneskoester approved these changes

2022-01-26 14:40 UTC, merged