added wrapper for using tabix to query an indexed file
snakemake/snakemake-wrappers pull request #203
Opened 2020-09-25 06:22 UTC by williamrowell

The current tabix wrapper can only be used to index a file, but tabix can also be used to query an indexed file, like `tabix -h my.vcf.gz chr1 > chr1.vcf.gz` or `tabix coverage.bed.gz chr20 > chr20.bed.gz`.  Added this as a separate wrapper.

2020-11-30 10:25 UTC, johanneskoester requested changes
Thanks a lot! Please add a test case to `test.py`.

2021-11-27 07:11 UTC, williamrowell commented
I added test cases and reformatted a few of these old PRs, but there are merge conflicts because my test.py files are out of date.  I'm not sure of the least complicated way to straighten this out.

2021-12-05 04:25 UTC, williamrowell commented
I've updated this and added a test case.  It's ready for review.

2022-01-26 14:41 UTC, johanneskoester approved these changes

2022-01-26 14:41 UTC, merged