Homer annotatepeaks
snakemake/snakemake-wrappers pull request #206
Opened 2020-09-30 14:44 UTC by AntonieV

A new wrapper for Homer annotatePeaks.pl.

2020-10-05 14:51 UTC, jafors requested changes
Holy cow, that's an impressive wrapper. Very detailed for all cases. For now, I have just a very small addition.

2020-10-05 14:51 UTC, jafors commented on bio/homer/annotatePeaks/wrapper.py
> +    if i and not i == "":
```suggestion
for i in opt_files:
    if i:
```

2020-10-05 14:51 UTC, jafors commented on bio/homer/annotatePeaks/wrapper.py
> +    if i and not i == "":
`i and not i == ""` is a tautology, `if i:` is totally sufficient here.

2020-10-06 19:38 UTC, AntonieV commented on bio/homer/annotatePeaks/wrapper.py
> +    if i and not i == "":
Many thanks for reviewing the PR and your comments.

2020-10-07 16:05 UTC, dlaehnemann approved these changes
Very impressive wrapper, indeed. Just two little suggestion for an improvement. But in any case good to go!

2020-10-07 16:05 UTC, dlaehnemann commented on bio/homer/annotatePeaks/wrapper.py
> +        extra += " {flag} {file}".format(flag=opt_files[i], file=i)
Instead of loading every possible input explicitly above, we could implicitly load and check them here:
```suggestion
    file = snakemake.input.get(i, "")
    if file:
        extra += " {flag} {file}".format(flag=opt_files[i], file=file)
```

2020-10-07 20:14 UTC, AntonieV commented on bio/homer/annotatePeaks/wrapper.py
> +        extra += " {flag} {file}".format(flag=opt_files[i], file=i)
Many thanks for reviewing and your suggestions, it looks much cleaner and more compact! Some additional adjustments were necessary for this.

2020-10-08 10:17 UTC, jafors approved these changes

2020-10-09 11:23 UTC, merged