added wrapper for dada2 learnErrors function
snakemake/snakemake-wrappers pull request #211
Opened 2020-10-05 13:51 UTC by cpauvert

This time I used the example data from the R package because my handmade examples were too small and importing data was too costly in terms of disk space.
Best,

2020-10-06 13:07 UTC, cpauvert commented
Contrary to recent changes in PR #207 (2022b4b370fd2a64f7be4b7f7bcbe7bc996eddd1), here, the `expand()` is necessary as the error learning algorithm picks sequences within the pool of samples.

2020-10-22 14:18 UTC, dlaehnemann requested changes
Great to see such a clean R snakemake wrapper. Just a bunch of suggestions that should be easy to address. Thanks a bunch!

2020-10-22 14:18 UTC, dlaehnemann commented on bio/dada2/learn-errors/environment.yaml
> +  - bioconductor-dada2 == 1.16.0
Unless a fixed patch version is necessary for a particular reason, I would unpin it so user get the latest security patches and bug fixes whenever they newly create an environment. I.e.:
```suggestion
  - bioconductor-dada2 == 1.16
```

2020-10-22 14:18 UTC, dlaehnemann commented on bio/dada2/learn-errors/wrapper.R
> +library(dada2, quietly=TRUE)
I think it's alright if the library loading gives output. This will simply end up in the log files and might help debugging installation issues. Same below for loading `ggplot2`.

2020-10-22 14:18 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/filtered/b.1.fastq
> +a.1.fastq
Is it intended, that this does not contain any reads but instead only the string `a.1.fastq`?

2020-10-22 14:18 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Maybe add an empty `params: extra = ""` with a comment, indicating that users can specify extra options. If available, with a link to docs that showcase the available options?

2020-10-22 14:18 UTC, dlaehnemann commented on bio/dada2/learn-errors/meta.yaml
> +    rev: a list of quality filtered and trimmed reverse FASTQ files (potentially compressed)
Optimally, the keys here would correspond to named `input` (lists) in the example Snakefile. Also, would it be possible to also include a (second) paired-end example in the Snakefile? From the current example, I wouldn't be sure how exactly to set it up.

2020-10-22 14:18 UTC, dlaehnemann commented on bio/dada2/learn-errors/wrapper.R
> +}
Maybe make this explicitly look for `snakemake@params[['extra']]` and add that if present? Otherwise, a user might specify multiple things under `params` and wonder why only the first ever gets added.

2020-10-22 14:18 UTC, dlaehnemann commented on bio/dada2/learn-errors/meta.yaml
> +    rev: a list of quality filtered and trimmed reverse FASTQ files (potentially compressed)
And if you add a second example rule for the paired-end case, you could use it to showcase that the plot can also be another format, e.g.: `plot="reports/dada2/errors_1.pdf`.

2020-10-23 09:05 UTC, cpauvert commented on bio/dada2/learn-errors/environment.yaml
> +  - bioconductor-dada2 == 1.16.0
Thank you for your nice words and your review @dlaehnemann ! The trailing 0 wasn't necesary, I will have to modify it in the others PR too.

2020-10-23 09:05 UTC, cpauvert commented on bio/dada2/learn-errors/wrapper.R
> +library(dada2, quietly=TRUE)
Ok! It makes more sense. I agree.

2020-10-23 09:07 UTC, cpauvert commented on bio/dada2/learn-errors/test/filtered/b.1.fastq
> +a.1.fastq
Yes, it is only a symlink to the `a.1.fastq` file. I didn't wanted to increase the size of the wrapper unnecessarily *but* at the same time illustrate that more than one samples are needed at this step. But I would welcome any others suggestions.

2020-10-23 09:08 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Sure, that would makes it more clear, thanks. I will do that!

2020-10-23 09:09 UTC, cpauvert commented on bio/dada2/learn-errors/wrapper.R
> +}
This is linked to the other issue in the Snakefile. Two birds one stone in the next commit

2020-10-23 09:36 UTC, cpauvert commented on bio/dada2/learn-errors/meta.yaml
> +    rev: a list of quality filtered and trimmed reverse FASTQ files (potentially compressed)
> Optimally, the keys here would correspond to named `input` (lists) in the example Snakefile. 

Oups I'm sorry, these keys are remnant from a previous version and were not updated. 

> Also, would it be possible to also include a (second) paired-end example in the Snakefile? From the current example, I wouldn't be sure how exactly to set it up.

Actually, this step can be executed no matter the read orientation. So it is possible, I can add another rule example wiht this case.

2020-10-23 10:31 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/filtered/b.1.fastq
> +a.1.fastq
I think these files are small enough to simply have proper files in both cases. Otherwise, users that dig into the recipe might be confused (even though that is very unlikely, I guess).

2020-10-23 12:35 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Actually, for R to receive properly the parameters, they have to be passed as a Python dictionary, as in the following example (1) not (2):
```
params: extra = { verbose = True, minLength = [200, 250] }         (1)
# params: verbose = True, minLength = [200, 250]  # will not work  (2)
```
That is why I did not initially added an empty `params: extra = ""` but I could add an empty `params: extra= {}` and test within the wrapper if the user entered a list, otherwise if the user entered something like (2), the wrapper could raise a warning and print the correct specifications.
What do you think?

2020-10-23 13:53 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Hmm, that's tricky. Does (2) not properly nest stuff, so you can't e.g. access `snakemake@params[['minLength']][[1]]`? If so, this probably calls for a fix upstream in `snakemake` itself, as I'm sure the intention would be for the R data structure to mirror the python data structure (including its nesting) and to allow for systematic access to all levels.

2020-10-23 14:03 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/Snakefile
> +        expand("filtered/{sample}.1.fastq", sample=["a","b"])
Do I understand this correctly, in that you can simply input a list of fastq files and it will generate a joint error model on all of them? So I could input single-end data from one sample or paired-end data from one sample or any combination thereof for any number of samples?

Also, another suggestion: Make it compressed (`fastq.gz`) for the example. Users will usually copy-paste the example rule into their workflows, and this will encourage use of compressed input data. If their input data comes compressed, it saves a step of uncompressing (if they overlook the comment, which many will;). And if it doesn't come compressed, it will encourage them to compress it and save space on their file system.

2020-10-23 14:12 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
The nesting is done properly, so I think Snakemake is fine. But the issue is more to have a non redundant way to pass arguments to a R function. AFAIK, you can't do the following in R:

```
optional<-list( verbose = TRUE, minLength = c(200, 250))
yourFunction(input=snakemake@input, output=snakemake@output, optional)
```
And even worse if optional is empty, which could be the case with optional parameters.

Looking at others R wrappers I saw two approaches. Either be fully explicit (and redundant) by copying all the R arguments of the needed functions into the Snakemake `params:` word. Or be transparent and pass arguments in a character string that would be further interpreted with the R functions `parse()` and `eval()`.

I wanted something more flexible and decided to rely on the R function `do.call()` which enables the execution of a function based on arguments provided as named list (see 6.2.4 from [Hadley's Advanced R](https://adv-r.hadley.nz/functions.html#function-fundamentals)).
Using such structure, I could pass a Python dictionary to Snakemake `params:` that would then be interpreted as a named lists in R.
That's why I went with this solution. I hope I was clear, and perhaps there is some R or Snakemake magic that I don't know of :)

2020-10-23 15:19 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Thanks for the clear explanation of the situation and the link. I like the idea of using `do.call()`, so let's try and make that work!
I would say, let the user specify as many (valid) arguments as they want via `params`, as the syntax will almost be the same as in R function calls, with only the quotes added (`params: argument_name=value`, so your previous (2) would become: `params: verbose="TRUE", minLength="c(200, 250)"`). This should be easy enough on the user if we provide an example or two in the example rule.
So the tricky part then is to get this list of parameters into an R `named list` through some iteration over all the keys in `params` proper handling of the `string`s that snakemake provides as values (for example turning the string `"TRUE"` into `TRUE` and the string `"c(200, 250)"` into the actual R vector `c(200, 250)`). I think, for turning strings into actual R code, the `library('rlang')` is our friend, with the [`parse_expr()` function](https://rlang.r-lib.org/reference/parse_expr.html). And then for creating the named list, [this Stack Overflow response should be helpful](https://stackoverflow.com/a/7599451). And passing in an empty (named) list (whenever no `params` are specified) should be fine as well, right?
Does this (together with iterating over all entries in `snakemake@params`) take you all the way, or am I still missing some stumbling block? If we get this to work, this recipe can be a good example R wrapper for more involved function calling. And eventually this could go into a `snakemake-wrapper-utils` R package as a generic function to parse all `params` into a named list, equivalent to the [respective Python package that has just been created](https://github.com/snakemake/snakemake-wrapper-utils)---although I think creating this might be a bit more complicated than the Python package.

2020-10-25 17:37 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Cool if you're ok with the `do.call()` and thank you for your involvement! I have to admit I'm not fond of the following syntax `params: verbose="TRUE", minLength="c(200, 250)"`. I think this syntax is neither Python nor R and usually parsing strings in R in not recommended when you can do differently AFAIK.
Reading again your message, I wondered if I explained myself clearly I am sorry. So far, the wrapper **can** take the `params:` from the Snakefile (or even the absence of `params:`), using the Python dictionary. I tried to put up a small reproducible example [here](https://github.com/cpauvert/r-snake-reprex) with some possibilities (no `params:` , with `params: {}` and with parameters specified) for illustration.
But perhaps I misunderstood that you think this Python dictionary is not a proper way to have people enter their parameters. In that case, we can still sort out a proper solution.
Do tell me, 
Best, 
Charlie

2020-10-27 07:48 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +        expand("filtered/{sample}.1.fastq", sample=["a","b"])
> Do I understand this correctly, in that you can simply input a list of fastq files and it will generate a joint error model on all of them? So I could input single-end data from one sample or paired-end data from one sample or any combination thereof for any number of samples?

Exactly @dlaehnemann 

> Also, another suggestion: Make it compressed (`fastq.gz`) for the example. Users will usually copy-paste the example rule into their workflows, and this will encourage use of compressed input data. If their input data comes compressed, it saves a step of uncompressing (if they overlook the comment, which many will;). And if it doesn't come compressed, it will encourage them to compress it and save space on their file system.

Yes it makes more sense. I, too, am a copy paste user ^^

2020-10-27 07:54 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +        expand("filtered/{sample}.1.fastq", sample=["a","b"])
Done in 34393bc

2020-10-27 08:03 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +        { 'randomize': True } # Optional parameters
As per our discussion on parameters @dlaehnemann.
Optional parameters can be passed to the R function using this Python syntax.
Removing the arguments between the `{ }` is handled without error. Removing the `params:` warns the user that the default options of the wrapped R function are used.
I hope that it is more clear this way,
Best, 
Charlie

2020-10-27 12:35 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Yes, I do see your point about the syntax. But I also think that explicitly asking users to create a dictionary under `params` is not really the `snakemake wrapper` way, as it will introduce structure where you usually only have strings. I am not really sure what the best option is, but then maybe resort to one string that specifies the named list with R syntax, i.e. something like:
```
    params:
        extra='list(verbose=TRUE, minLength=c(200,250))'
```
This way, users can provide extra arguments to the function and do so in R syntax. Simply wrapped in a string that is then parsed as an R expression. And the function itself should usefully complain about anything that is not specified properly (unknown arguments, syntax errors?).

2020-10-27 13:10 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
> Yes, I do see your point about the syntax. But I also think that explicitly asking users to create a dictionary under `params` is not really the `snakemake wrapper` way, as it will introduce structure where you usually only have strings.

Thanks for the explanation, I did not consider it that way. Obviously, I don't want to mess with the established approach. So I guess we could go for the parse R syntax. I like your suggestion of the list this way. I don't think however that the rlang package is a necessary dependency as we would be parsing only lists with usually simple arguments. I'll provide a suggestion right away.

2020-10-27 13:29 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Ok I tested the new syntax on a reprex with R `plot()` ([here](https://github.com/cpauvert/r-snake-reprex/commit/777933a2197c2c3fd45a83289ad46d18061369e9)) and it works fine.
I will implement it in this wrapper.

2020-10-27 13:52 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +        { 'randomize': True } # Optional parameters
Not necessary anymore (1e83b57)

2020-10-27 13:52 UTC, cpauvert commented on bio/dada2/learn-errors/wrapper.R
> +}
I made it explicit in 1e83b57

2020-10-27 13:52 UTC, cpauvert commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Done in 1e83b57

2020-10-27 13:57 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Yeah, one dependency less is always a good idea, especially if the basic syntax is still readable! Let me also double-check with @johanneskoester, in case he has a better idea for a more `snakemakey` syntax, here. But generally, I think we found a good way of doing this!

2020-10-28 09:04 UTC, cpauvert commented
I rebase the branch to resolve the conflict on the file `test.py`

2020-10-28 09:39 UTC, dlaehnemann requested changes
It seem like simply using `snakemake@params` with `do.call()` should have worked all along. Once we have this, I think the wrapper will be good to go -- and we will have a great best-practice example of how to implement this for an R wrapper!

2020-10-28 09:39 UTC, dlaehnemann commented on bio/dada2/learn-errors/test/Snakefile
> +    log:
Sorry that this took another day. But of course, @johanneskoester did have very useful input. He pointed me to the `REncoder` code in Snakemake:
https://github.com/snakemake/snakemake/blob/70d3c74dfb2b52b1ed314d865eb362454304da44/snakemake/script.py#L112

Effectively, this means that the `snakemake@params` available in the R script automagically is a named list, converting Python booleans to R booleans and Python lists to R lists. Thus, using Python syntax with named arguments under `params` and then simply concatenating `snakemake@params` to the other `args` before calling `do.call()` should actually do the job. So, my suggestion would be to make this clear in a comment above params in R wrappers where extra parameters / named arguments can be used. Something like this:
```
    # Even though this is an R wrapper, use named arguments in Python syntax here, to specify extra
    # parameters. Python booleans (`arg1=True`, `arg2=False`) and lists (`list_arg=[]`) are automatically 
    # converted to R. For a named list as an extra named arguments, use a python dict (`named_list={name1=arg1}`).
    params:
        randomize=True
```

Should a wrapper ever need to handle any of the named arguments differently (i.e. not as an extra argument to the function, but to handle some other logic), it can simply test for the presence of that named item in the list and remove (and handle) it before the `do.call()`.

2020-10-28 09:54 UTC, cpauvert commented
Don't worry, it's better to take time and be satisfied in the end! Thanks to you both @dlaehnemann and @johanneskoester !
Yes, I knew the magic happened (though not how) for `snakemake@params` named list. However, the named list is duplicated and not named but rather numbered which means the direct concatenation fails (I tried a while ago). We just need to sort out only the named list from `snakemake@params` and we're good.

2020-10-28 12:18 UTC, dlaehnemann approved these changes
Very cool, we now have a good example to point to for future R wrappers. We'll be updating the contribution documentation soon, and I'll make sure to point to this example!

2020-10-28 12:19 UTC, merged

2020-10-28 12:20 UTC, cpauvert commented
Great! Thanks @dlaehnemann! I'm updating the others as well.

2020-10-28 12:36 UTC, dlaehnemann commented
Jup. Let me know once you're done and I'll plow through those, as well!

2020-10-28 12:48 UTC, cpauvert commented
> Jup. Let me know once you're done and I'll plow through those, as well!

Ok I'll do it. The main issue would be for me to resolve the conflicts with `test.py` that will happen after every merge. Do you have perhaps any pro tips regarding that?

2020-10-28 12:58 UTC, dlaehnemann commented
Hmm, not really. One thing that might help, is that you can resolve these conflicts right here on GitHub in the pull request. That might make it a bit quicker. And another idea would be to add the tests in different places in `test.py`, so that the edits do not potentially conflict. But as these are all dada2 wrappers, putting them in different places probably doesn't make too much sense...