added dada2 wrapper for dada (aka sample inference) function
snakemake/snakemake-wrappers pull request #217
Opened 2020-10-13 14:40 UTC by cpauvert

Hi,
A small wrapper in line with the started `dada2` integration into wrappers. Parameters can be passed to the R function with a Python dictionary.
Best,
Charlie

2020-11-01 16:52 UTC, dlaehnemann requested changes
Just some minor suggestions, should be quickly addressed. This process is getting much smoother... :D

2020-11-01 16:52 UTC, dlaehnemann commented on bio/dada2/sample-inference/meta.yaml
> +name: dada2_learn_errors
This is the same as for the `dada2/learn-errors` wrapper. Shouldn't this instead read something like:
```suggestion
name: dada2_sample_inference
```

2020-11-01 16:52 UTC, dlaehnemann commented on bio/dada2/sample-inference/meta.yaml
> +  - derep: RDS file withe the dereplicated sequences
Typo:
```suggestion
  - derep: RDS file with the dereplicated sequences
```

2020-11-01 16:52 UTC, dlaehnemann commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Just a thought: You chose the same name for the input file as for the function argument name with `derep`, maybe do the same here (for consistency;):
```suggestion
        err="results/dada2/model_1.RDS" # Error model
```
Obviously, the `wrapper.R` needs the respective adjustment...

2020-11-01 16:52 UTC, dlaehnemann commented on bio/dada2/sample-inference/meta.yaml
> +name: dada2_learn_errors
Or simply `dada2_dada` instead. As `dada` is the function that is called by this wrapper.

2020-11-02 10:36 UTC, cpauvert commented on bio/dada2/sample-inference/meta.yaml
> +name: dada2_learn_errors
Oups that was a typo, thanks for spotting it! As for the name, I preferred to name the rule as per the step name in the [tutorial](https://benjjneb.github.io/dada2/tutorial.html) rather than the function. In order to ease the readability for the (coming soon) meta-wrapper ;)

2020-11-02 10:46 UTC, cpauvert commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Yes that's possible. However, I just called it `model=` in the `dada2_learn_errors` rule earlier :/ What do you suggest. Change both?

2020-11-02 10:50 UTC, dlaehnemann commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Ah, yeah. It should be consistent in that sense, as well. So unless this disagrees with any named parameters in `dada2_learn_errors`, I would go for changing both.

Maybe you can start a final dada2 cleanup PR that will only be finalised and merged once all the individual PRs are merged? This way we can collect changes to already merged PRs in one place and reduce the number PRs we need to track.

2020-11-02 10:58 UTC, dlaehnemann commented on bio/dada2/sample-inference/meta.yaml
> +name: dada2_learn_errors
So `sample_inference` [works here](https://benjjneb.github.io/dada2/tutorial.html#sample-inference), right?

You might just want to double-check in the end. I changed the name of wrapper (6/10), that also had `dada2_learn_errors` to `dada2_merge_pairs` and you might want to go for `dada2_merge_paired_reads`, [according to the tutorial](https://benjjneb.github.io/dada2/tutorial.html#merge-paired-reads). So maybe something for the cleanup PR, as well (see below).

2020-11-02 11:01 UTC, cpauvert commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Yeah sorry about that. Perfect! I like the idea of a final cleanup PR!

2020-11-02 11:23 UTC, dlaehnemann commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
No worries. That's exactly what all these code reviews are for.

2020-11-02 11:26 UTC, dlaehnemann commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Also, one more thought for the cleanup: It seems like you can link to sections of the tutorial, by appending `#all-lower-caps-section-title-with-dashes-for-whitespace`. So with the names already corresponding to the tutorial section, it might be nice to adjust the links at the start of the description to point to the respective tutorial sections. E.g.:
https://benjjneb.github.io/dada2/tutorial.html#merge-paired-reads

What do you think?

2020-11-02 17:31 UTC, cpauvert commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Hum nice suggestion but the manual provide the additional arguments whereas the tutorial doesn't. However I found out that I could pinpoint to the function within the manual using this:


https://www.bioconductor.org/packages/release/bioc/manuals/dada2/man/dada2.pdf#derepFastq

We could keep the link to the tutorial for the meta-wrapper then.
What do you think?

2020-11-02 17:39 UTC, dlaehnemann commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Yes, you're right. For the optional arguments, we should point to the PDF manual.

So maybe point to both the PDF manual and the tutorial, simply adding a sentence about the tutorial?

The PDF-link doesn't seem to work for me. It opens the PDF, but doesn't jump to the function's help section. So maybe it's browser-specific (I'm using Firefox)

2020-11-02 17:44 UTC, cpauvert commented on bio/dada2/sample-inference/meta.yaml
> +  - derep: RDS file withe the dereplicated sequences
Done in the last commit! Thanks

2020-11-02 17:45 UTC, cpauvert commented on bio/dada2/sample-inference/test/Snakefile
> +        model="results/dada2/model_1.RDS" # Error model
Ok too bad. Yes I can add both links then ;)

2020-11-02 17:51 UTC, dlaehnemann approved these changes
Looking good!

2020-11-02 17:52 UTC, merged