Wrapper for bowtie2-build
snakemake/snakemake-wrappers pull request #221
Opened 2020-10-14 14:42 UTC by standage

The `bowtie2` aligner is already included in Snakemake wrappers, but this PR adds a wrapper for the `bowtie2-build` command.

2020-10-14 15:31 UTC, standage commented
Ready for review!

2020-10-21 12:32 UTC, dlaehnemann requested changes
Thanks for adding this missing wrapper! It generally looks good, I just have a couple of suggestions to further improve it.

2020-10-21 12:32 UTC, dlaehnemann commented on bio/bowtie2/build/environment.yaml
> +  - bowtie2 ==2.4.1
Maybe unpin the patch version, unless this particular patch version is needed (e.g. for a version-specific index or something?)?
```suggestion
  - bowtie2 =2.4
```

2020-10-21 12:32 UTC, dlaehnemann commented on bio/bowtie2/build/wrapper.py
> +    "{snakemake.input[0]} {snakemake.params.base}"
You could refer directly to the reference input by name:
```suggestion
    "{snakemake.input.reference} {snakemake.params.base}"
```

2020-10-21 12:32 UTC, dlaehnemann commented on bio/bowtie2/build/test/Snakefile
> +    log:
I would say this calls for the use of the [snakemake `multiext()` function](https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#the-multiext-function).

2020-10-21 12:32 UTC, dlaehnemann commented on bio/bowtie2/build/test/Snakefile
> +        base="genome",  # prefix for index files
Instead of specifying the same basename as in `output` here via `params`, I would rather parse `snakemake.output[0]` to strip off the specific extension in `wrapper.py` and then pass the resulting `base` to bowtie. This way there's no risk that the `output` spec and a separate `base` spec can be different and break the wrapper.

2020-10-21 13:10 UTC, standage commented on bio/bowtie2/build/environment.yaml
> +  - bowtie2 ==2.4.1
I'd be happy to do so, but the bowtie2 align wrapper pins this particular version. In any case, I suggest that these two wrappers should be consistent.

2020-10-21 13:17 UTC, standage commented on bio/bowtie2/build/test/Snakefile
> +    log:
Done in 5d33a4b.

2020-10-21 13:17 UTC, standage commented on bio/bowtie2/build/test/Snakefile
> +        base="genome",  # prefix for index files
Is the change in 5d33a4b what you had in mind?

2020-10-21 13:18 UTC, standage commented on bio/bowtie2/build/wrapper.py
> +    "{snakemake.input[0]} {snakemake.params.base}"
Done in 5d33a4b.

2020-10-21 14:18 UTC, dlaehnemann commented on bio/bowtie2/build/environment.yaml
> +  - bowtie2 ==2.4.1
Jep, that sounds perfectly reasonable. So lets keep it pinned as is and these should then be updated in sync. Maybe we can add a comment here (and correspondingly in the `align` wrapper's `environment.yaml`), noting this -- thus whenever anyone does an update, they are reminded to do it in sync:
```suggestion
  # if you update this version, please also update the version at bio/bowtie2/align/environment.yaml
  - bowtie2 ==2.4.1
```

2020-10-21 14:20 UTC, dlaehnemann commented on bio/bowtie2/build/test/Snakefile
> +        base="genome",  # prefix for index files
Jup, exactly the right amount of automagic behaviour! :D

2020-10-21 14:54 UTC, standage commented on bio/bowtie2/build/environment.yaml
> +  - bowtie2 ==2.4.1
Done in 8fd850d.

2020-10-21 15:52 UTC, dlaehnemann approved these changes
Looks good. Thanks again!

2020-10-21 15:53 UTC, merged