Added main plink v1.9 functionality for GWAS
snakemake/snakemake-wrappers pull request #229
Opened 2020-10-15 23:29 UTC by adRn-s

This is the latest version available at bioconda. Hopefully it will help bioinformaticians and other professionals to screen variants and their phenotypical outcome(s).

More info: <https://www.cog-genomics.org/plink/1.9/>

2020-10-22 15:03 UTC, dlaehnemann requested changes
Thanks for this contribution! It looks like there's a quite a bit of complexity to handle for PLINK.

I have provided some suggestions and questions. And also one major point:
This is currently missing tests. These should be easy to implement in `test.py` with the example `Snakefile`s and data files you already provide.

2020-10-22 15:03 UTC, dlaehnemann commented on bio/plink/preprocess/wrapper.py
> +    " --recode {extra_recode} --out {prefix} \n"
Can `--recode` also be set as a flag without any argument specified in `extra_code`? With the current example Snakefile, `extra_code` is simply an empty string `""` which would be pasted in here.

2020-10-29 02:11 UTC, adRn-s commented on bio/plink/assoc/environment.yaml
> +  - plink =1.90b4
The version bump from `b4` to `b6` went through while I was working on this. Let's unpin to `plink =1.90`.

2020-11-02 21:04 UTC, adRn-s commented on bio/plink/assoc/test/Snakefile
> +        output_prefix="plinkdata",
I understand that would be optimal if plink were using extensions without extra dots. Sadly, the plink output files extensions are for example, ".assoc.fisher" when using the "fisher-midp" extra option and ".assoc.fisher.mperm" when using two extra options, one to apply mid p-value correction and another for using permutations.

Here's an example of this difficulty:

```
>>> a = '/home/user/algo.otro.jpg'
>>> os.path.split(a)
('/home/user', 'algo.otro.jpg')
>>> os.path.basename(a)
'algo.otro.jpg'
>>> os.path.basename(a)[::-1]
'gpj.orto.ogla'
>>> os.path.splitext(os.path.basename(a)[::-1])
('gpj.orto', '.ogla')
>>> [ x[::-1] for x in os.path.splitext(os.path.basename(a)[::-1]) ]
['otro.jpg', 'algo.']
```

That almost made it, even if it's not elegant. Any thoughts? Thanks for your time.

2020-11-02 21:38 UTC, adRn-s commented on bio/plink/preprocess/wrapper.py
> +    " --recode {extra_recode} --out {prefix} \n"
Yes, the `extra_recode` is an empty string but here I tried to make available the [extra options for this parameter](https://www.cog-genomics.org/plink/1.9/data#recode) even if they're infrequently used.

2020-11-02 21:46 UTC, adRn-s commented on bio/plink/preprocess/wrapper.py
> +covariables = snakemake.params.get("covariables", "")
I'm not sure about this. Most of these preprocessing parameters are kind of mandatory and some of them (i.e. CSV file sex column name and its encoding "M/F" or "1/2" or "XX/XY" or etc.) vary greatly between users. I'd rather have empty strings and hopefully error message prompted if no value is provided could hint the user that s/he needs to specify better.

2020-11-02 21:53 UTC, adRn-s commented on bio/plink/preprocess/test/Snakefile
> +        extra_file="--make-just-fam",
You really have a sharp eye, kudos. True, this could be a problem but actually the `preprocess/wrapper.py` I wrote issues two `plink` commands. The second one makes the `map` and `ped` files (using the VCF) and the first call is the one using the `extra_file` parameter. If the user changes that option for an empty string `map` and `ped` would be written by the first command and then overwritten by the second one, so there's no problem here.

2020-11-02 21:58 UTC, adRn-s commented on bio/plink/preprocess/test/Snakefile
> +        extra_file="--make-just-fam",
If the user changes that option for an empty string the problem arises. I mean, I'll have to hardcode the `--make-just-fam` in `wrapper.py` and we're good.

2020-11-02 22:11 UTC, adRn-s commented on bio/plink/linear/wrapper.py
> +    covar = " --covar {extra_covar} {prefix}.cov "
Right. I ended up using another "heuristic", instead of checking if the user is providing a ".cov" file I will check if `len(covar_names) > 0` since that's the key to using covar, you can have multiple covariables in a same `.cov` file but plink will only use the one defined in that parameter.

2020-11-03 10:28 UTC, dlaehnemann commented on bio/plink/preprocess/wrapper.py
> +    " --recode {extra_recode} --out {prefix} \n"
From what I understand from the linked docs, these options will change the output type, as well, right? And wherever this is reflected in an extension, this should also be handled by specifying the respective extension in `output:`, with the `--recode` modifier automagically set by the wrapper. And only modifiers that change the format while keeping the extension the same then need to be handled by `params: extra_recode="modifiers"`.

2020-11-03 11:05 UTC, dlaehnemann requested changes
Thanks for the update. I have some more suggestions and hope they are clear. If not, feel free to ask!

2020-11-03 11:05 UTC, dlaehnemann commented on bio/plink/assoc/meta.yaml
> +name: plink
This name should be specific to the command, otherwise users will get confused in the menu. So something like:
```suggestion
name: plink_assoc
```

2020-11-03 11:05 UTC, dlaehnemann commented on bio/plink/assoc/meta.yaml
> +description: PLINK is a variant association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner. https://www.cog-genomics.org/plink
This description should be specific to the command and also contain a link to the specific subcommand that this wrapper implements. Otherwise users won't know which exact command this wrapper handles and will have a hard time finding out where exactly to find documentation.

2020-11-03 11:05 UTC, dlaehnemann commented on bio/plink/assoc/meta.yaml
> +  - Plink format file(s) with genotype information.
Here, I would describe which file (types) are required and which ones are optional. If certain file types are incompatible, this should also be mentioned. And if certain file types will implicitly set certain options, I would document this here.

2020-11-03 11:10 UTC, dlaehnemann commented on bio/plink/preprocess/wrapper.py
> +    " --recode {extra_recode} --out {prefix} \n"
But generally I also understand now, that `--recode` is basically something like a subcommand, as are the likes of `--assoc` etc. That's a funny syntax, but hey... :D

2020-11-03 11:12 UTC, dlaehnemann commented on bio/plink/preprocess/wrapper.py
> +covariables = snakemake.params.get("covariables", "")
Sure, error messages that make sure that required parameters are set are a good idea. I would also mention required parameters in the `meta.yaml` and probably mark them as required in the example rule with a comment, for example:
```
    params:
        # required parameter
        sex_column = "sex"
```

2020-11-03 11:20 UTC, dlaehnemann commented on test.py
> +
Instead of the `-F`, it is clearer what you are testing if you actually ask for at least one of the output files for each rule. Theoretically, you can also have several tests for one rule, with different sets of output requested. This is especially important for automagic output file extension handling that implicitly sets options for a command.

2020-11-03 11:21 UTC, dlaehnemann commented on bio/plink/preprocess/test/Snakefile
> +        extra_file="--make-just-fam",
But will the user always want `--make-just-fam` set? Shouldn't this be optional and simply depend on whether only the `.fam` file is specified in `snakemake.output`?

2020-11-03 11:27 UTC, dlaehnemann commented on bio/plink/linear/wrapper.py
> +    covar = covar[:-2] + " "
If you want to make parsing a bit easier, here, you could also simply make `covar_names` a string in the example, where multiple names of covariates are comma separated (`"covar1, covar2"`), just like a user would specify them on the command line. Then this becomes:
```suggestion
    covar = " --covar {prefix}.cov {extra_covar} --covar-name {covar_names} "
```

2020-11-03 14:35 UTC, adRn-s commented on bio/plink/assoc/wrapper.py
> +prefix2 = getPlinkName(snakemake.output[0])
The problem is that plink uses output extensions to indicate options used in the command. So, for example the ".assoc.fisher" is there every time we use `fisher-midp` extra option to activate that correction. But user's may change this.

I will run some tests now, maybe I can split by "assoc" to extract the correct basename/ prefix.

2020-11-03 18:12 UTC, adRn-s commented on bio/plink/assoc/wrapper.py
> +# prefix_out_ext = "qassoc"
Is it okay if I implement this loading the file with pandas?

Shall I add pandas as a dependency in `plink/assoc/environment.yaml`?

2020-11-03 18:57 UTC, dlaehnemann commented on bio/plink/assoc/wrapper.py
> +prefix2 = getPlinkName(snakemake.output[0])
Jep, users should be able to change this by specifying the `.assoc.fisher` output extension. The `wrapper.py` should then check whether that is extension is among `snakemake.output` and if so, add the `fisher-midp` extra option to the shell command. Is that description somewhat comprehensible?

2020-11-03 19:01 UTC, dlaehnemann commented on bio/plink/assoc/wrapper.py
> +# prefix_out_ext = "qassoc"
Jep, if you need to parse the FAM file like this, this sounds reasonable. And also jep for adding pandas as a dependency. Snakemake will usually have it along, but any environment should be self-sufficient in its dependencies.

2020-11-10 16:55 UTC, adRn-s commented
I believe this is complete now.

2020-11-10 20:03 UTC, dlaehnemann requested changes
We're getting there...

I think I have three main suggestions that apply for most of the wrappers in this PR and which I have highlighted on some of them:

1. I would generally prefer simple `os.path.splitext(snakemake.output[0])` parsing and the likes to get to prefixes. This makes this parsing more general, should extensions longer than 3 letters ever come up.
2. I would actually prefer named input arguments over `multiext()` (did I suggest that earlier, if so: sorry!), as they will provide more flexibility in input naming in case users may want it. And it makes them available by name via `snakemake.input.named_input` syntax. If this makes any part of parsing `snakemake.output` easier, feel free to also go for named outputs.
3. All the named params in the different wrappers should be explained in some way. One option is `# comments` in the `Snakefile`, right above a certain named `params:` entry. Another option is explaining them in `meta.yaml`. In either case, I would put a link to the respective documentation somewhere, so that users can quickly check it to know what to put where.

2020-11-10 22:59 UTC, adRn-s commented
Regarding https://github.com/snakemake/snakemake-wrappers/pull/229#discussion_r520835254 

Lacking default values for the column names at CSV data sounds natural to me. Specially for `pheno_column`.

2020-11-10 23:15 UTC, adRn-s commented on bio/plink/assoc/wrapper.py
> +    basenames = [x[:-4] for x in pathList]
We're making the ped/ fam/ map files from the custom preprocess subcommand. Whoever changes their extension might be trying to break functionality, in such case we won't be able to prevent that.

2020-11-10 23:26 UTC, adRn-s commented on bio/plink/assoc/wrapper.py
> +prefix_out = get_prefix_str(snakemake.output, prefix_out_ext)
The difficulty I was trying to address is that output files have extensions fixed by PLINK and they change in regards to the options in use. For example, if user tests association using permutations and fisher correction it gets: `*.assoc.fisher` and `*.assoc.fisher.mperm` (just as in 'assoc' rule provided at test Snakefile).

The `os` module can't handle that efficiently. 

```>>> os.path.splitext("file.assoc.fisher")
('file.assoc', '.fisher')
```

That's why I'm also forcing `multiext()`... actually it's PLINK functionality that enforces using "--out {prefix}" to its users and this wrapper can't change that.

2020-11-10 23:30 UTC, adRn-s commented on bio/plink/assoc/wrapper.py
> +    " --ped {prefix_in}.ped --map {prefix_in}.map"
It's PLINK functionality that enforces using "--out {prefix}". See [here](https://www.cog-genomics.org/plink/1.9/output).

2020-11-10 23:33 UTC, adRn-s commented on bio/plink/linear/wrapper.py
> +    covar = f" --covar {prefix}.cov {extra_covar} --covar-name {covar_names} "
I believe it's OK.

```
>>> str([1, 2, 3])[1:-1]
'1, 2, 3'
```

2020-11-11 14:33 UTC, adRn-s commented on bio/plink/linear/wrapper.py
> +if len(covar_names) > 0:
Every plink subcommand (assoc, model, linear or logistic) has a rule/ wrapper and needs a previous mandatory preprocess rule (that it can be shared) for converting genotype and phenotype information available as plink files (ped, map, fam). This logic is present in the test Snakefiles to anyone willing to use the wrappers. Any user of Plink knows about ped/ fam/ map filetypes; the downloaded binaries bring a toy dataset in these specific file formats. 

I wouldn't split the `multiext` function and underlying logic.

2020-11-11 16:09 UTC, dlaehnemann commented on bio/plink/linear/wrapper.py
> +    covar = f" --covar {prefix}.cov {extra_covar} --covar-name {covar_names} "
The difference would be this:
```
>>> list = ['1', '2', '3']
>>> str(list)[1:-1]
"'1', '2', '3'"
>>> ','.join(list)
'1,2,3'
```
So one question is: Is the command-line OK with each element being single quoted (`'2'`) and with the spaces after each comma (I would expect arguments to be either comma-separated, or space separated -- but usually not both at the same time).
And the other question is readability. I've never seen the conversion of a list to a string with the stripping via array indices, but I've seen the `.join()` version a lot.

2020-11-11 16:12 UTC, dlaehnemann commented on bio/plink/assoc/wrapper.py
> +    " --ped {prefix_in}.ped --map {prefix_in}.map"
Yeah, but this only refers to the input. The prefix for the output should be taken from `snakemake.output[0]` or a named `snakemake.output.assoc_mperm`.

2020-11-11 16:27 UTC, dlaehnemann commented on bio/plink/assoc/wrapper.py
> +prefix_out = get_prefix_str(snakemake.output, prefix_out_ext)
Then maybe also go for named output (`output: assoc="path/to/plink.assoc", assoc_mperm="path/to/plink.assoc.mperm") and simply do this:
```
prefix_out = snakemake.output.assoc.split(sep='.assoc')[0]
```

And regarding different outputs, I understand from the example Snakefile above, that `fisher-midp` on the command-line switches the output to contain the `.fisher` part of the suffix. The general way that Snakemake wrappers handle this, is that they will inspect the extensions of the output or the names of named outputs to decide whether such an option is set or not. So with the current example rules you provide, you would remove the `fisher-midp` from `params.extra_assoc` and instead auto-magically set it when the output files contain `assoc.fisher`, so something like:
```
if any(outfile.endswith('.fisher') for outfile in snakemake.output):
    extra_assoc = "fisher-midp {}".format(extra_assoc)
```

2020-11-11 16:31 UTC, dlaehnemann commented on bio/plink/linear/wrapper.py
> +if len(covar_names) > 0:
Is there no possible scenario, where a user might want to create any of the input files (ped, fam, map) or intermediate files of the pipeline with a different tool or custom script? If you can rule this out, sticking to the fixed `multiext` could be reasonable to keep the input and output specification streamlined. At the same time, named inputs and outputs offer you easier parsing of file names to get to prefixes and extensions, with the latter necessary for automagical setting of necessary command line arguments.

2020-11-11 16:39 UTC, dlaehnemann commented
> Regarding [#229 (comment)](https://github.com/snakemake/snakemake-wrappers/pull/229#discussion_r520835254)
> 
> Lacking default values for the column names at CSV data sounds natural to me. Specially for `pheno_column`.

I think I don't understand this answer. In the comment you link to, I was asking about [my comment right before](https://github.com/snakemake/snakemake-wrappers/pull/229/files#r516589938). And the point I was making there, were:
1. Please add information on all the required named `params:` entries in `meta.yaml`, including some link to PLINK documentation that explains how to set them (some of the `meta.yaml`s contain such linkouts to docs, others don't -- please also add such links where they are missing).
2. Please add comments above each `params:` entry in the example Snakefile that explain whether an entry is a `# required parameter` or an `# optional parameter`. This way, after copy-pasting the example rule invocation, users will know which options they can skip and which ones they really need to set. With a link to the respective docs set via `meta.yaml` they will then also find information on how to set them properly.

I hope the explanations this round are comprehensible? If not, please let me know what remains unclear and where I should maybe provide more concrete examples.

2020-11-12 18:19 UTC, adRn-s commented on bio/plink/linear/wrapper.py
> +    covar = f" --covar {prefix}.cov {extra_covar} --covar-name {covar_names} "
Yes, the `.join()` makes whole sense in Python.

2020-11-12 18:48 UTC, adRn-s commented on bio/plink/assoc/wrapper.py
> +prefix_out = get_prefix_str(snakemake.output, prefix_out_ext)
I like this idea a lot, yet not all extra options have a clear `1:1` mapping with PLINK's given extra extensions. I'd stick with having the named `extra_` parameters and passing them to the subcommand. The central contribution in these wrappers is in regards to the `preprocess` wrapper and its handling of standard formats input data (VCF, CSV). The other subcommand wrappers have to do with the actual testing using PLINK and the tool has its own established interface and documentations for its users.

2020-11-12 19:00 UTC, adRn-s commented on bio/plink/linear/wrapper.py
> +if len(covar_names) > 0:
I do rule out the possibility. Still it's not imposible for users to make an intermediary rule with a custom script to modify PED file (for example). They'd only need to overwrite their file to keep its path intact.

Any study is expected to have one and only one well defined PED/ FAM/ MAP file(s) representing their data. The only natural way of not doing it like that would be if you where to run the analysis pipeline using only a subset of the samples.. maybe. Even in such case, that would be better done upstream of `preprocess` in the VCF and CSV files.

2020-11-12 19:03 UTC, adRn-s commented on bio/plink/preprocess/wrapper.py
> +covariables = snakemake.params.get("covariables", "")
> Sure, error messages that make sure that required parameters are set are a good idea. I would also mention required parameters in the `meta.yaml` and probably mark them as required in the example rule with a comment, for example:
> 
> ```
>     params:
>         # required parameter
>         sex_column = "sex"
> ```

I now see the comment. Sorry, I will address it in the next commit.

2020-11-13 10:17 UTC, dlaehnemann commented on bio/plink/assoc/wrapper.py
> +prefix_out = get_prefix_str(snakemake.output, prefix_out_ext)
Well, wherever you can auto-magically handle something based on extensions, I would do that. Otherwise you can have an extension and the options provided in `params` fields disagree, whenever users are not careful to keep both in sync. And the default way to handle something should always be via `input` and `output` fields, wherever possible (as that is what snakemake needs to be accurate for delineating dependencies).
Wherever something about the output generation is changed by a command-line argument without changing the general file type (and thus the extension), this should be specified via `params`.
Does this distinction make sense?

2021-02-22 16:24 UTC, dlaehnemann commented
Just wondering about the status of this PR. There's a lot of work in this one, so I'm hoping we could take this to merging? @adRn-s, do you still have plans for this PR?

2021-02-22 23:03 UTC, adRn-s commented
Yes. I would really like to have this PR merged. The last few times (i.e. commits) that I run tests locally the code and pipeline interface were OK.

At first, I felt a little dazzled after all the comments and corrections. I understand that this code is a lot better now (comparing to my first commit), but honestly I felt demotivated after the last proposals. Furthermore, I can't discern between what really needs adjusting.

How shall we proceed?

2021-02-22 23:11 UTC, adRn-s commented
Shall we start from a fresh point? review #293

2021-02-23 10:13 UTC, dlaehnemann commented
Yeah, I know that feeling. Sorry that that my review made you feel that way, this was definitely not intended. And yes, a fresh start sounds like a good idea. let's switch over to #293 .

2021-02-23 10:13 UTC, closed without merging