Bwa genome prefix automatic fill #228
snakemake/snakemake-wrappers pull request #232
Opened 2020-10-19 07:42 UTC by tdayris

Hi,

This is an implementation of enhancement request #228 

Many thanks in advance for your reviews

PS: I'm still having this Template merge from PR #187 . I shall not have merged it to my master branch

2020-10-22 15:32 UTC, dlaehnemann requested changes
I really like the new behaviour and the backwards compatibility. I have some suggestions to update the example rules in the `Snakefile`s accordingly. But I also just realised, that PR #186 also addresses this. Could you double check whether you can contribute anything to the review over there? And if that PR addresses everything you're looking for, maybe close this PR here?

The changes regarding wrapper code rendering should be fine, as they are already in master in exactly the same way. No clue, why they get highlighted again.

2020-10-22 15:32 UTC, dlaehnemann commented on bio/bwa-mem2/index/wrapper.py
> +    prefix = splitext(snakemake.output[0])[0]
In correspondence with this change, I would also remove the `params.prefix` specification from the example `Snakefile` here:
https://github.com/tdayris/snakemake-wrappers/blob/661f288e5f1d150c35ca8e910c5a3fb59ef9c4a4/bio/bwa-mem2/index/test/Snakefile#L13-L14

Same for `prefix` and `index` in the other recipes. I like the idea of backward compatibility of the wrapper code, in case someone simply updates the wrapper version. But new users that copy paste the example rule from the Snakefile should have the automagic behaviour without risking that the prefix and output specs go out of sync.

2020-10-22 15:32 UTC, dlaehnemann commented on bio/bwa-mem2/mem-samblaster/wrapper.py
> +    index = path.splitext(snakemake.input["index"])[0]
I guess this is intended as the standard future use, right? I would then update the example rule in the Snakefile to contain an `input: index="someindex.some_index_extension"` accordingly.

2020-11-30 10:29 UTC, johanneskoester commented on bio/bwa-mem2/mem-samblaster/wrapper.py
> +    index = path.splitext(snakemake.input["index"])[0]
Actually the input should list all index files, by making use of the [multiext helper](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=multiext#the-multiext-function).

2020-12-02 09:53 UTC, tdayris commented on bio/bwa-mem2/index/wrapper.py
> +    prefix = splitext(snakemake.output[0])[0]
Changes have been made in the Snakefiles, thanks you!

2020-12-02 09:55 UTC, tdayris commented on bio/bwa-mem2/mem-samblaster/wrapper.py
> +    index = path.splitext(snakemake.input["index"])[0]
You are right, miltiext is now displayed in the snakefiles.

2021-05-27 15:47 UTC, dlaehnemann approved these changes
Looks good, now. I'll have a look why the tests are failing.

2022-01-26 14:27 UTC, merged