Unicycler
snakemake/snakemake-wrappers pull request #233
Opened 2020-10-19 08:56 UTC by tdayris

Hi,

Unicycler is an assembler based on Spades. It handles both short and long reads and handles circular plasmids.

`samtools`, `pilon`, `racon`, `bcftools`, and `blast` are dependencies required for optional unicycler process (*e.g.* long read processing, ...)

Thank you in advance for your reviews

2020-10-22 15:54 UTC, dlaehnemann requested changes
Looks very good. Just some minor suggestions for improvements. Thanks a lot!

2020-10-22 15:54 UTC, dlaehnemann commented on bio/unicycler/environment.yaml
> +  - unicycler ==0.4.8
As always, I'm for unpinning the patch version of packages unless any tool needs to be on a specific patch version for a particular reason. :D

2020-10-22 15:54 UTC, dlaehnemann commented on bio/unicycler/test/Snakefile
> +        "result/assembly.fasta"
Maybe make this a bit more abstract, add a `log:` entry and an empty `params.extra` to showcase that this can be used to pass further arguments, e.g.:
```suggestion
    input:
        paired = expand("reads/{{sample}}.{read}.fq.gz", read=["R1", "R2"])
    output:
        "result/{sample}.fasta"
    log:
        "logs/{sample}.log"
    params:
        extra=""
```

2020-10-22 15:54 UTC, dlaehnemann commented on bio/unicycler/wrapper.py
> +    input_reads += " --long {} ".format(snakemake.input["long"])
Ah, OK. I see the complexity, now. I would then opt for several example rules in the Snakefile that showcase different options, for example:

1. Short paired-end reads only.
2. Short paired-end and unpaired and long reads all together in one rule.

And maybe use a list in an input named `paired` instead of `short1` and `short2` separately? But that is a question of taste, I guess.

2020-10-22 15:54 UTC, dlaehnemann commented on bio/unicycler/meta.yaml
> +description: Assemble bacterial genomes with Unicycler
I always like a link to the docs for quick reference.

2020-10-22 15:54 UTC, dlaehnemann commented on test.py
> +                    success = True
Is this an intended change? Or simply `black` doing its job?

2020-11-02 13:50 UTC, tdayris commented on test.py
> +                    success = True
You are right, I blacked this file as I initially did a formatting error.

2020-11-02 13:52 UTC, tdayris commented on bio/unicycler/meta.yaml
> +description: Assemble bacterial genomes with Unicycler
Link to documentation has been added. 

I totally agree with you on **always** adding documentation and/or citation. I think this may be a future PR I'll apply for.

2020-11-02 13:55 UTC, tdayris commented on bio/unicycler/wrapper.py
> +    input_reads += " --long {} ".format(snakemake.input["long"])
Short1 and Short2 have now been paired together as you suggested. Further examples will soon be added as you advised

2020-11-02 14:03 UTC, tdayris commented on bio/unicycler/environment.yaml
> +  - unicycler ==0.4.8
I do not agree on this one. Even though patches usually contains minor bug fixes, it is important to my team to master every single patch version (*e.g.* for ISO standards, clinics and personal-medicine related projects).

Samtools, GATK, FastQC, Salmon, etc. All of them have patch version pinned in their respective wrappers.

2020-11-02 15:17 UTC, tdayris commented on bio/unicycler/test/Snakefile
> +        "result/assembly.fasta"
You're right, changes have been made according to your suggestions. Thanks!

2020-11-02 15:18 UTC, tdayris commented on bio/unicycler/wrapper.py
> +    input_reads += " --long {} ".format(snakemake.input["long"])
Examples have been added. Thanks again for your review!

2020-11-02 15:45 UTC, dlaehnemann commented on bio/unicycler/environment.yaml
> +  - unicycler ==0.4.8
I guess samtools, gatk, fastqc and salmon could or should be unpinned.

But your other argument is new to me and an important one. I would still think that you would want to get security patches and bug fixes, even in a clinics setting (or especially in such a setting). And you could still ensure consistency of results via some sort of continuous integration testing. But obviously, you have the respective hands-on experience and will know better about all the complicated details of this sort of environment.
So maybe you want to chime into this (very) recent Stackoverflow question regarding version pinning and elaborate your use case further, so it gets documented more permanently (as comments to the question, the answer, or as an altogether different answer):
https://stackoverflow.com/questions/64594146/best-practices-for-bioconda-versions-in-snakemake-wrappers

2020-11-02 15:51 UTC, dlaehnemann approved these changes
Looks good!

And I guess the [pinning / unpinning discussion](https://github.com/snakemake/snakemake-wrappers/pull/233#discussion_r516063570) is for another day. But please do chime in on it over at Stackoverflow:
https://stackoverflow.com/questions/64594146/best-practices-for-bioconda-versions-in-snakemake-wrappers

2020-11-02 16:25 UTC, merged