add meta-wrapper dada2-pe
snakemake/snakemake-wrappers pull request #249
Opened 2020-11-03 15:06 UTC by cpauvert

Hi, 
Some recently  included dada2 wrappers were bundled together to make this meta-wrapper (**pe**-version). Changes from the wrapper codes includes:

* Adjustments of filenames and add onstart message
* Necessary example files for the meta-wrapper
* Add test in test.py

Docs and local test runs fine.

However,  I have an open question so far (maybe @dlaehnemann), I want to summarize the number of reads and ASV throughout the different rules (just like in the [tutorial](https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline) and my scripts). Initially, I planned to add in the meta-wrapper a `stats` rule that would parse all output file using an R script and output a table/plot.
But I figured that the awesome [reporting](https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html) ability of Snakemake could fit the job perfectly. But I'm not sure if I have to modify every wrapper code to report something, or could I had reporting rules to the meta-wrapper Snakefile?

Best, 
Charlie

2020-11-03 15:56 UTC, dlaehnemann commented
Regarding your question:

Using the `report()` directive is definitely a good idea. All you have to do, is to wrap the final output of the stats summary rule (somr plot or a table) in that function and provide a file that defines a description (which can use the snakemake object to parse in `input`, `output`, `params`, `wildcards`, etc.). Then, all you have to do, is to call `snakemake --report` once the pipeline has finished successfully. However, with the extra rst and the idea of running a whole pipeline through before creating a report, it sounds more like you might want to create a full-blown [snakemake workflow](https://github.com/snakemake-workflows/docs) (which can make use of this meta-wrapper, of course).

Also, if you only want it as a quality control measure, double-check if there's a [`multiqc`](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/multiqc.html) module that can automatically deal with the dada2 outputs. Maybe someone else has already done your job... ;)

I'll review the meta-wrapper later.

2020-11-03 16:08 UTC, cpauvert commented
> Regarding your question:
> 
> Using the `report()` directive is definitely a good idea. All you have to do, is to wrap the final output of the stats summary rule (somr plot or a table) in that function and provide a file that defines a description (which can use the snakemake object to parse in `input`, `output`, `params`, `wildcards`, etc.). Then, all you have to do, is to call `snakemake --report` once the pipeline has finished successfully. However, with the extra rst and the idea of running a whole pipeline through before creating a report, it sounds more like you might want to create a full-blown [snakemake workflow](https://github.com/snakemake-workflows/docs) (which can make use of this meta-wrapper, of course).

Ok thanks for the precision. I planned to use the snakemake workflow model at some point but I was just wasn't sure where to modularize and where to externalize. But you've provided a clear answer, thanks!
> 
> Also, if you only want it as a quality control measure, double-check if there's a [`multiqc`](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/multiqc.html) module that can automatically deal with the dada2 outputs. Maybe someone else has already done your job... ;)

I'll look into it! thanks

> I'll review the meta-wrapper later.

No problem :)

2020-11-03 17:03 UTC, dlaehnemann commented
Well, the question where and how to modularize is still a growing consensus, I'd say. So if you have different ideas, please try them out and let the world know! :D

If there for example is a multiqc module for dada2, you could simply include a multiqc rule in the meta-wrapper.

2020-11-04 07:48 UTC, cpauvert commented
Turns out there isn't a dedicated multiqc module for DADA2; So I'll opt for the report within the (soon to come) snakemake workflow and will stick to the following definitions:

* Wrapper: one tool
* Meta-wrapper: several tools/wrappers linked
* Workflow: meta-wrapper(s) and reporting (and config files)
Best, 
Charlie

2020-11-04 11:23 UTC, cpauvert commented
I just corrected a wildcard in `sample_inference` so that the error models of forward **and** reverse were correctly use for the corresponding samples.

I will set the PR ready for review again when #250 will be included for the inclusion of this missing wrapper would be safer in the meta-wrapper.
Best,

2020-11-04 17:34 UTC, cpauvert commented
The new wrapper is included and the all meta-wrapper is updated :)

2020-11-05 08:13 UTC, cpauvert commented
I will change the demo dataset to include `cutadapt` in this meta-wrapper and make it more embedded with existing wrappers!

2020-11-05 09:23 UTC, cpauvert commented
> I will change the demo dataset to include `cutadapt` in this meta-wrapper and make it more embedded with existing wrappers!

Never mind.. I thought of using the mock communities at https://github.com/caporaso-lab/mockrobiota but all have their primers already removed.

2020-11-12 18:20 UTC, dlaehnemann reviewed
Generally looks good, I just have some questions and suggestions.

2020-11-12 18:20 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +    print("Do it after the quality profile checks.")
I hope I am understand this correctly, feel free to adjust to whatever meaning was intended.

```suggestion
    print("Make sure that you set the `truncLen=` option in the rule `dada2_filter_and_trim_pe` according")
    print("to the results of the quality profile checks (after rule `dada2_quality_profile_pe` has finished on all samples).")
```

2020-11-12 18:20 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +        touch("reports/dada2/quality-profile/quality_check.done")
Why do you need this rule? Couldn't you simply include its input `expand()` statement in the `rule all` instead of the output of this rule?

2020-11-12 18:20 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +        "results/dada2/taxa.RDS"
You could add the output of `dada2_quality_profile_pe` here, and suggest that users comment out the other output in a first run:
```
        # In a first run of this meta-wrapper, comment out all other inputs and only keep this one.
        # Looking at the resulting plot, adjust the `truncLen` in rule `dada2_filter_trim_pe` and then
        # rerun with all inputs uncommented.
        expand(
            "reports/dada2/quality-profile/{sample}-quality-profile.png",
            sample=["a","b"]
        )

2020-11-12 18:20 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +    input: expand("results/dada2/model_{orientation}.RDS", orientation=[1,2])
What does this rule do? It does not generate any output, so it can never be run - the only rule with no output is the rule `all`. So maybe you intended to add its input to the rule `all`?

2020-11-12 18:20 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +    input: expand("results/dada2/model_{orientation}.RDS", orientation=[1,2])
Or should this error model be used as input to another rule somewhere?

2020-11-12 18:20 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +    input: expand("results/dada2/model_{orientation}.RDS", orientation=[1,2])
Ah no, `dada2_sample_inference` already uses it, so no need for this rule.

2020-11-13 07:57 UTC, cpauvert commented
Thanks @dlaehnemann for your review. I'm quite busy today so I might not respond to your suggestions right away, sorry.
Best, 
Charlie

2020-11-20 08:00 UTC, cpauvert commented on meta/bio/dada2_pe/meta.yaml
> +  A subworkflow for processing paired-end sequences from metabarcoding projects in order to construct ASV tables using ``DADA2``.  The example are built on the data provided in the ``R`` package. For
Yes that's better! Thanks!

2020-11-20 08:01 UTC, cpauvert commented on meta/bio/dada2_pe/test/Snakefile
> +    print("Do it after the quality profile checks.")
Better correction indeed

2020-11-20 08:03 UTC, cpauvert commented on meta/bio/dada2_pe/test/Snakefile
> +        touch("reports/dada2/quality-profile/quality_check.done")
Thanks for the suggestion, I will implement it! I had this weird inital idea that the `rule all` should be clean and with a few targets

2020-11-20 08:16 UTC, cpauvert commented on meta/bio/dada2_pe/test/Snakefile
> +    input: expand("results/dada2/model_{orientation}.RDS", orientation=[1,2])
I removed it also! thanks!

2020-11-20 08:17 UTC, cpauvert commented
Thank you @dlaehnemann for your review. Here is the cleaned version.
Best, 
Charlie

2020-11-20 08:53 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +        touch("reports/dada2/quality-profile/quality_check.done")
Nah, chuck it all in there! ;) It's the one endpoint that you can have a look at to know what the pipeline / meta-wrapper will output.

2020-11-20 10:09 UTC, dlaehnemann approved these changes
Looks good!

2020-11-20 10:09 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +        # FASTQ file without primers sequences
Typo:
```suggestion
        # FASTQ file without primer sequences
```

2020-11-20 10:09 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +        # Paired-end files without primers sequences
Typo:
```suggestion
        # Paired-end files without primer sequences
```

2020-11-20 10:13 UTC, dlaehnemann commented
@cpauvert Could you try to merge the most recent master branch into this branch, and then push this? We've had a couple of GitHub Actions updates, so I would hope that the failures go away with the most recent version.

2020-11-20 10:30 UTC, cpauvert commented
That should be good now. The branch was way behind (my bad)

2020-11-20 10:35 UTC, cpauvert commented
This is strange. Locally the meta-wrapper with the test data ran smoothly. But the GithubActions indicates that the wrapper was not modified and this seems to be the only cause of failure
https://github.com/snakemake/snakemake-wrappers/pull/249/checks?check_run_id=1430192053#step:7:372
Have you ever ran into such error?

2020-11-20 10:39 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +        # FASTQ file without primers sequences
```suggestion
        # FASTQ file without primer sequences
```

2020-11-20 10:39 UTC, dlaehnemann commented on meta/bio/dada2_pe/test/Snakefile
> +        # Paired-end files without primers sequences
```suggestion
        # Paired-end files without primer sequences
```

2020-11-20 10:43 UTC, dlaehnemann commented
Hmm, it looks like that merge did not work as intended, but you simply reverted the last commit that I did to the branch online. Here are the commands that should do the job:
```
git checkout master
git pull
git checkout meta-pe
# get the last commit that I did online
git pull
git merge master
git push
```
In this process, no force push should be needed, as everything should simply be handled as regular commits that add to the history. And I am hoping that once the newest changes from master are actually in here, the errors should go away (or be solvable more easily;).

2020-11-20 10:49 UTC, cpauvert commented
My bad, my rebase was quite messy.
Looking around what's changed in the `test.py` it appears that the invocation of the meta-wrapper did not follow the new convention (especially the `@skip_if_not_modified`) so I change that and replace it correctly. Hope it will do!

2020-11-20 11:10 UTC, dlaehnemann commented
Your update seems right. But now it seems to simply skip testing the meta-wrapper, even though the meta-wrapper definitely has changed (well, it didn't exist on the master branch before, but that does imply a change;). So I think something is not working quite right with the skipping of meta-wrappers. Probably because each of the individual wrappers didn't change, the whole meta-wrapper isn't tested.

2020-11-20 11:11 UTC, dlaehnemann commented
Sorry for the extra complication with this, I think we'll have to double-check meta-wrapper testing behaviour, here.

2020-11-20 12:46 UTC, cpauvert commented
No worry! Indeed the test was skipped. Do you want me to revert the last commit and remove the flag above the function to try to trigger the test?

2020-11-20 12:51 UTC, dlaehnemann commented
Jep, maybe that's a good idea. And @johanneskoester will fix this shortly, so that another merge in from the master branch should do the job. Hopefully with minimal cleanup on your part, afterwards.

2020-11-25 09:54 UTC, johanneskoester requested changes
Great work, just a few final things. Also, the master branch should now be fixed to properly run the meta-wrapper tests. Can you please update to latest master and see if the test is executed properly?

2020-11-25 09:54 UTC, johanneskoester commented on meta/bio/dada2_pe/test/Snakefile
> +    print("If in doubt, check https://benjjneb.github.io/dada2/tutorial.html#inspect-read-quality-profiles")
Please just mention this as a comment. People who use the meta-wrapper can then decide how to ensure that via their config file setup.

2020-11-25 09:54 UTC, johanneskoester commented on meta/bio/dada2_pe/test/Snakefile
> +    #   (`named_list={name1=arg1}`).
These comments can be omitted. The latest meta-wrapper template now includes hints on how to find additional configuration parameters for each wrapper, so that we don't need to repeat this here.

2020-11-25 11:00 UTC, cpauvert commented on meta/bio/dada2_pe/test/Snakefile
> +    print("If in doubt, check https://benjjneb.github.io/dada2/tutorial.html#inspect-read-quality-profiles")
Alright! Will do.

2020-11-25 11:06 UTC, cpauvert commented on meta/bio/dada2_pe/test/Snakefile
> +    #   (`named_list={name1=arg1}`).
Removed in the last commit.

2020-11-25 11:07 UTC, cpauvert commented
Thanks for the review and the recent changes. I updated the PR and crossing fingers for the test!

2020-11-30 08:31 UTC, johanneskoester approved these changes

2020-11-30 08:31 UTC, merged

2020-11-30 08:37 UTC, cpauvert commented
Thanks for the merge @johanneskoester !

2020-11-30 15:08 UTC, dlaehnemann commented
@cpauvert Just following up on the big work you put in for the dada2 wrappers and meta-wrappers, and on your plans to implement a workflow at some point. @jafors just spotted a Snakemake workflow using DADA2 that has been published today:

[Dadasnake, a Snakemake implementation of DADA2 to process amplicon sequencing data for microbial ecology](https://doi.org/10.1093/gigascience/giaa135)

But they're not using the wrappers and the workflow is currently in a dedicated repository. We thought this might be the perfect opportunity to team up with @a-h-b for a version 2.0 that uses wrappers and meta-wrappers. And just maybe gets added to the [Snakemake Workflow repo](https://github.com/snakemake-workflows/docs)... ;)

2020-11-30 17:46 UTC, cpauvert commented
Thanks @dlaehnemann but all the work was made possible with your insights too! Yes, I was aware of this nice initiative. I'll bump into the discussion there and give it a thought ;)