updates author information and minimum fastp version
snakemake/snakemake-wrappers pull request #264
Opened 2020-11-13 06:53 UTC by skurscheid

2020-11-20 11:42 UTC, johanneskoester requested changes

2020-11-20 11:42 UTC, johanneskoester commented on bio/fastp/environment.yaml
> +  - fastp >=0.20.0
We cannot be sure about future releases. For provenance reasons, wrapper envs should always pin at least to minor versions.

2020-11-20 11:42 UTC, johanneskoester commented on bio/fastp/environment.yaml
> +  - fastp >=0.20.0
```suggestion
  - fastp =0.20
```

2020-11-20 12:17 UTC, skurscheid reviewed
Sure, sounds absolutely reasonable and will keep this in mind!

2020-11-25 09:35 UTC, johanneskoester approved these changes

2020-11-25 09:35 UTC, merged