Bamtools split wrapper.
snakemake/snakemake-wrappers pull request #282
Opened 2021-01-26 10:27 UTC by Smeds

2021-01-26 11:51 UTC, jafors requested changes
Thanks for the work, this should be a valuable addition! Find some small remarks below.

2021-01-26 11:51 UTC, jafors commented on bio/bamtools/split/test/Snakefile
> +        split_type="-reference",
Could you add an `extra` field here, if someone wants to use other flags like `-refPrefix`?

```suggestion
    params:
        #  -reference is the default value and can be left out, could also be '-paired' and '-tag <tag_name>'
        split_type="-reference",
        extra=""
```

2021-01-26 11:51 UTC, jafors commented on bio/bamtools/split/wrapper.py
> +__email__ = "koester@jimmy.harvard.edu"
You can give your own mail address here. ;)

2021-01-26 11:51 UTC, jafors commented on bio/bamtools/split/wrapper.py
> +shell("bamtools split -in {snakemake.input} " + split_type + " {log}")
```suggestion
shell("bamtools split -in {snakemake.input} {split_type} {log}")
```

2021-01-26 12:19 UTC, Smeds commented on bio/bamtools/split/wrapper.py
> +__email__ = "koester@jimmy.harvard.edu"
Done

2021-01-26 12:19 UTC, Smeds commented on bio/bamtools/split/test/Snakefile
> +        split_type="-reference",
Changed split_type to extra

2021-01-26 12:20 UTC, Smeds commented on bio/bamtools/split/wrapper.py
> +shell("bamtools split -in {snakemake.input} " + split_type + " {log}")
Changed split_type to extra

2021-01-29 20:57 UTC, johanneskoester approved these changes

2021-01-29 20:57 UTC, merged