Added GATK VariantEval wrapper
snakemake/snakemake-wrappers pull request #305
Opened 2021-03-05 14:31 UTC by fgvieira

2021-03-19 12:25 UTC, jafors requested changes
Thanks for the addition! I have added some remarks, feel free to comment if you disagree!

2021-03-19 12:25 UTC, jafors commented on bio/gatk/varianteval/wrapper.py
> +    bam = list(map("--input {}".format, bam))
Maybe we should allow `input.vcf` and `input.bam` to be strings if only one sample is used. You could check if they are strings or lists and act accordingly. Sth like

```
vcf = snakemake.input.vcf
if isinstance(vcf, str):
    vcf = "--eval  {}".format(vcf)
else:
    vcf = list(map("--eval {}".format, vcf))
```

2021-03-19 12:25 UTC, jafors commented on bio/gatk/varianteval/wrapper.py
> +
Maybe we should also add a `--comp` input for comparison vcfs, similar to the bam input.
See [here](https://gatk.broadinstitute.org/hc/en-us/articles/360040507171-VariantEval-BETA-#--comparison)

2021-03-19 12:25 UTC, jafors commented on bio/gatk/varianteval/test/Snakefile
> +        vcf=["calls/snvs.vcf"],
As mentioned in the `wrapper.py`, I feel this should be able to be a string in single sample runs.

2021-03-23 08:42 UTC, johanneskoester approved these changes

2021-03-23 08:48 UTC, merged