Hap.py
snakemake/snakemake-wrappers pull request #317
Opened 2021-03-26 16:03 UTC by nate-d-olson

snakemake wrapper for main hap.py benchmarking functionality for https://github.com/snakemake/snakemake-wrappers/issues/294. This is my first attempt at creating a snakemake-wrapper, recommendations and suggestions for adhering to best practices are appreciated.

2021-03-29 13:10 UTC, nate-d-olson commented
Any recommendations for removing `params.prefix`, causing the code quality limiting error, when the prefix is used for multiple output files?

2021-03-29 13:13 UTC, jafors requested changes
Hey! I'll start with some linting issues (see below).

2021-03-29 13:13 UTC, jafors commented on bio/hap.py/hap.py/environment.yaml
> +  - rtg-tools = 3.10.1
```suggestion
  - hap.py ==0.3.14
  - rtg-tools ==3.10.1
```

2021-03-29 14:15 UTC, jafors commented
> Any recommendations for removing `params.prefix`, causing the code quality limiting error, when the prefix is used for multiple output files?

I'd suggest inferring it from one of the output names. In your case, you would need to get the "results" from the complete file name. You can access wildcards, input and output inside of `params` using the a lambda function.
```
params:
    prefix=lambda wc, input, output: output[0].split('.')[0]
```
This should do the trick, since all output files start with the same prefix. You can however also be more specific and use for example `output["runinfo"]` instead of `output[0]`.

2021-03-29 15:55 UTC, nate-d-olson commented
Thanks @jafors for your help addressing the code quality issues. In this case for the outputs is it better to use the `multiext` function to ensure the output files have all the same prefix or define them individually. Then use the lambda expression to define the suggested lambda expression to define the prefix.

2021-03-29 17:33 UTC, jafors requested changes
In total, the wrapper looks already pretty good, but since hap.py has multiple optional arguments, we could go for some generalizations.

2021-03-29 17:33 UTC, jafors commented on bio/hap.py/hap.py/wrapper.py
> +    " --engine {snakemake.params.engine}"
If I understand hap.py correctly, there is a default engine which is used if the `--engine` parameter is not given.
If that's the case, we also should have a default value for this, or even easier, just ignore the parameter if it is not given.
Sth. like:
```
engine = snakemake.params.get("engine", "")
if engine:
    engine = "--engine {}".format(engine)

shell(
    "(hap.py"
    " --threads {snakemake.threads}"
    " {engine}"
   ....
```

2021-03-29 17:33 UTC, jafors commented on bio/hap.py/hap.py/wrapper.py
> +    " --stratification {snakemake.input.strats}"
Similar to the engine, I think those are optional inputs, so the wrapper should be functional without them. You can use similar structures with `get()` as with params.

2021-03-29 17:56 UTC, nate-d-olson commented on bio/hap.py/hap.py/wrapper.py
> +    " --stratification {snakemake.input.strats}"
Since `truth_regions` and `stratifications` are input files, can I use `get()` with `snakemake.input` like this
 
```
truth_regions = snakemake.input.get("truth_regions")
if truth_regions:
    truth_regions = "-f {}".format(truth_regions)
```

2021-03-29 18:16 UTC, jafors commented on bio/hap.py/hap.py/wrapper.py
> +    " --stratification {snakemake.input.strats}"
Yes, this should work, you can use it with `input` as with `params`.

2021-03-29 20:50 UTC, johanneskoester approved these changes
Excellent work!

2021-03-30 06:15 UTC, jafors approved these changes

2021-03-30 06:15 UTC, merged