Automatically detect threads and output format
snakemake/snakemake-wrappers pull request #318
Opened 2021-03-30 09:47 UTC by fgvieira

These options are quite common across `bcftools` tools (and there might be others, like `tmp_dir` or `max_mem`) so, it might make sense to have them parsed on `snakemake_wrapper_utils`, just like it is currently done for `java`. The same could be done for `samtools`, (e.g.):

- `snakemake_wrapper_utils.bcftools`
- `snakemake_wrapper_utils.samtools`

2021-04-08 12:36 UTC, johanneskoester approved these changes

2021-04-08 12:37 UTC, johanneskoester commented
> These options are quite common across `bcftools` tools (and there might be others, like `tmp_dir` or `max_mem`) so, it might make sense to have them parsed on `snakemake_wrapper_utils`, just like it is currently done for `java`. The same could be done for `samtools`, (e.g.):
> 
> * `snakemake_wrapper_utils.bcftools`
> * `snakemake_wrapper_utils.samtools`

This is a very good idea. Do you want to provide a PR?

2021-04-08 13:27 UTC, fgvieira commented
Sure... I can give it a try. 😄

2021-04-20 16:05 UTC, johanneskoester requested changes
snakemake-wrapper-utils 0.2.0 has been released, you can add it to the env and make use of it.

2021-04-20 16:05 UTC, johanneskoester commented on bio/bcftools/concat/test/Snakefile
> +B65;6003;1crule bcftools_concat:
What happened here?

2021-04-20 18:40 UTC, fgvieira commented on bio/bcftools/concat/test/Snakefile
> +B65;6003;1crule bcftools_concat:
Uff, no idea... :)

2021-04-20 18:55 UTC, fgvieira commented
@johanneskoester I am getting an error that seems to be related to `snakemake`:
`ModuleNotFoundError: No module named 'stopit'`

2021-05-31 15:14 UTC, johanneskoester requested changes

2021-05-31 15:14 UTC, johanneskoester commented on bio/bcftools/concat/test/Snakefile
> +        bcftools_use_mem = False,
```suggestion
        bcftools_use_mem = False,  # if True, limit memory to given mem_mb resource
```
Is that the intended meaning of this? Maybe the parameter should be renamed to `bcftools_limit_mem` then?

2021-05-31 15:14 UTC, johanneskoester commented on bio/bcftools/concat/test/Snakefile
> +        bcftools_use_mem = False,
I know, this would need a change in snakemake-wrapper-utils

2021-05-31 22:31 UTC, fgvieira commented
Yes, the idea was to disable memory parsing, since `bcftools concat` does not support it.
However, I think it is better to disable it in the wrapper.

2021-06-01 10:23 UTC, johanneskoester approved these changes

2021-06-01 10:23 UTC, merged