Fixed bug when specifying queryname sorting
snakemake/snakemake-wrappers pull request #329
Opened 2021-04-03 09:31 UTC by fgvieira

and removed tmp file specification, since it can be done through `sort_extra`.

2021-05-28 20:28 UTC, dlaehnemann requested changes
Good catch and nice docs extensions.

However, I think keeping the `-T` setting is required to avoid race conditions.

2021-05-28 20:28 UTC, dlaehnemann commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort {sort_extra} -o {snakemake.output[0]} -"
Having this after potentially adding to `sort_extra` is a good idea. But I think the `-T` prefixing should remain in there, as well, as this will avoid multiple sorts happening in the same folder from accidentally generating the same `.tmp` files. So I'd also keep this:
```
    prefix = path.splitext(snakemake.output[0])[0]
    sort_extra += " -T " + prefix + ".tmp
```

2021-05-29 09:37 UTC, fgvieira commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort {sort_extra} -o {snakemake.output[0]} -"
The reason I removed it was that the user might sometimes want to have the temp files in another place (e.g. local scratch), rather than where the output is; and it can just be specified through `params.extra`.

But I guess we could check if the tmp folder is specified in `params.extra` and, if not, default to that.
Do you think that would make sense?

2021-05-29 09:45 UTC, dlaehnemann commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort {sort_extra} -o {snakemake.output[0]} -"
Ah, yes. Very good point. That makes perfect sense.

Something like `if "-T " in params.extra` should do the trick.

2021-05-29 10:15 UTC, fgvieira commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort {sort_extra} -o {snakemake.output[0]} -"
but actually, samtools already has a default temp:
```
-T PREFIX
Write temporary files to PREFIX.nnnn.bam, or if the specified PREFIX is an existing directory, to PREFIX/samtools.mmm.mmm.tmp.nnnn.bam, where mmm is unique to this invocation of the sort command.

By default, any temporary files are written alongside the output file, as out.bam.tmp.nnnn.bam, or if output is to standard output, in the current directory as samtools.mmm.mmm.tmp.nnnn.bam.
```

So it might be ok as is, no?

2021-05-31 07:18 UTC, johanneskoester commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort {sort_extra} -o {snakemake.output[0]} -"
I think samtools' default is not a good one, becuase we frequently see leftover files from that in case of crashes. Therefore, this rule should actually always default to some Python-driven TemporaryDirectory for the -T param, and not even expose it in my opinion.  What do you think?

2021-05-31 09:38 UTC, dlaehnemann commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort {sort_extra} -o {snakemake.output[0]} -"
I think I still had the problem in mind from older versions, where specifying a (tmp) folder as a prefix did not generate a unique infix. So it seems the situation is already much better. But I agree with @johanneskoester that handling this with a [python temporary directory](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) is best to avoid a mess after unexpected interruptions of job executions. This should give the directory as a prefix:
```
import tempfile

with tempfile.TemporaryDirectory() as prefix:
```

And then maybe add a check to `params.extra`, that `-T ` should not be used there.

2021-06-08 14:01 UTC, fgvieira commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort {sort_extra} -o {snakemake.output[0]} -"
Added python `tempdir` to both `samtools` and `picard`

2021-06-08 14:45 UTC, dlaehnemann requested changes
This generally looks good to me, thanks a bunch. Just two minor things.

2021-06-08 14:45 UTC, dlaehnemann commented on bio/bwa/mem/wrapper.py
> +tmp_prefix = path.splitext(snakemake.output[0])[0]
I don't think the `tmp_prefix` is needed. The `TemporaryDirectory()` will be unique and will exist once samtools is called, so there cannot be any race conditions, if I understand the handling of existing directories correctly from the [samtools sort manual](https://www.htslib.org/doc/samtools-sort.html).

```suggestion
```

2021-06-08 14:45 UTC, dlaehnemann commented on bio/bwa/mem/wrapper.py
> +    pipe_cmd = "samtools sort -T {tmp}/{tmp_prefix}.tmp {sort_extra} -o {snakemake.output[0]} -"
In line with my above comment, I would simply go for:
```suggestion
    pipe_cmd = "samtools sort -T {tmp} {sort_extra} -o {snakemake.output[0]} -"
```

2021-06-08 14:45 UTC, dlaehnemann commented on bio/bwa/mem/wrapper.py
> +    tempfile.tempdir = tmp_dir
That's a neat trick! :D

2021-06-08 14:45 UTC, dlaehnemann commented on test.py
> +        cmd = cmd + ["--wrapper-prefix", "file://{}/".format(d), "--conda-cleanup-pkgs", "--printshellcmds"]
Is this meant as a permanent change, or was this just for testing locally?

2021-06-08 14:57 UTC, fgvieira commented on test.py
> +        cmd = cmd + ["--wrapper-prefix", "file://{}/".format(d), "--conda-cleanup-pkgs", "--printshellcmds"]
I thought of it as a permanent change, as it can help debugging when you can see exactly what command is being run.

2021-06-08 15:01 UTC, fgvieira commented on bio/bwa/mem/wrapper.py
> +tmp_prefix = path.splitext(snakemake.output[0])[0]
I am not totally sure but, as I understood it, `TemporaryDirectory()` will return a temp directory (and create it) while `samtools sort` require a prefix (directory + part of the name). That was why I included the `tmp_prefix`.

But maybe it is not necessary...

2021-06-08 15:02 UTC, fgvieira commented on bio/bwa/mem/wrapper.py
> +tmp_prefix = path.splitext(snakemake.output[0])[0]
I'll accept your suggestions and we'll see if it works! :smile:

2021-06-08 15:09 UTC, dlaehnemann commented on test.py
> +        cmd = cmd + ["--wrapper-prefix", "file://{}/".format(d), "--conda-cleanup-pkgs", "--printshellcmds"]
You're right. Also, this is only displayed in the logs for failing tests. So it should be fine!

2021-06-08 15:10 UTC, dlaehnemann approved these changes

2021-06-08 15:11 UTC, merged