Added support for gz and bz2 fasterqdump output
snakemake/snakemake-wrappers pull request #330
Opened 2021-04-04 14:45 UTC by fgvieira

2021-04-22 14:43 UTC, johanneskoester requested changes

2021-04-22 14:43 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
TMPDIR I'd rather handle via Pythons temp functionality, which properly considers the usualy TMPDIR etc variables.

2021-04-22 14:43 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        extra="-v -v"
Is that a good default? If so, I'd at least use the long versions for readability.

2021-04-22 19:26 UTC, fgvieira commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        extra="-v -v"
It was mostly to illustrate the use of `extra`; just changed it.

2021-05-27 20:05 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
Those clusters simply need to configure TMPDIR I think. If the admins don't want that, you can do that in the cluster jobscript for example.

2021-06-08 20:29 UTC, johanneskoester requested changes

2021-06-08 20:54 UTC, fgvieira commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
I see your point, but I sometimes need to specify different temp folders for different rules (some rules create relatively small temp files, so I can use a local/faster temp folder; other require lots of temp space, and I have to use the shared filesystem; running on HPC clusters, the temp folder is node dependant; etc...).

For the HPC execution, we could set a `TMPDIR` variable that points to (e.g.) `/scratch/$PBS_JOBID`, but what if the rule requires a lot of temp space? How could we override `TMPDIR`?

2021-06-09 10:14 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
Ok, that makes a bit more sense, thanks for the clarification. Nevertheless, tmp space is a platform specific thing, so it should not be part of the workflow definition. Instead, we can add a solution via the Snakemake CLI.

So, do I read it correctly that there might be more than one desired tempdir location depending on the amount of temp space needed by the rule?

What if we add a new default resource `tmpdir`, which always points to whatever the default env variables yield (i.e. TMPDIR). But then, it can be overwritten by the CLI (see also this related PR for redefining resources via the CLI: https://github.com/snakemake/snakemake/pull/1041).

2021-06-09 10:44 UTC, fgvieira commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
Yes, as I see it, the temp location might change depending on space needed. Just to be clear, you suggest that by default `resources.tmp_dir` will be (e.g.) `TMPDIR` for all rules, but it can be overwritten by:
```
rule a:
    input:     ...
    output:    ...
    resources:
        mem_mb=100,
        tmpdir="/scratch/"
    shell:
        "..."
```
or 
```
snakemake --set-resources a:tmpdir=/scratch
```

Sounds good to me. :smile:

2021-06-09 10:46 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
Exactly. And Snakemake will automatically set all the typical environment variables inside the job when tmpdir is specified. That way, there is no need to handle this in a special way in the wrapper.

2021-06-09 10:55 UTC, fgvieira commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
The wrapper would just need to ensure to use `TMPDIR` appropriately, or use python's `tempfile` package (that deals with it automatically).
Definitely a cleaner solution.

2021-06-09 12:35 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
See here: https://github.com/snakemake/snakemake/pull/1042

2021-06-09 12:35 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
So, I would say the tmpdir handling can be removed from this wrapper.

2021-06-09 12:36 UTC, johanneskoester commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
Just keep the Python based tempdir creation and it should automatically use the correct path.

2021-06-09 21:12 UTC, fgvieira commented on bio/sra-tools/fasterq-dump/test/Snakefile
> +        tmp_dir="/tmp/",
Just committed the last changes

2021-06-10 10:58 UTC, johanneskoester approved these changes

2021-06-10 10:58 UTC, merged