Add vg giraffe
snakemake/snakemake-wrappers pull request #3302
Opened 2024-10-16 13:44 UTC by FelixMoelder

This adds `vg giraffe` for mapping reads as bam records.
Like for `bwa mem` sorting reads by samtools, picard or fgbio is supported. 

### QC

* [ ] I confirm that I have followed the [documentation for contributing to `snakemake-wrappers`](https://snakemake-wrappers.readthedocs.io/en/stable/contributing.html).

While the contributions guidelines are more extensive, please particularly ensure that:
* [ ] `test.py` was updated to call any added or updated example rules in a `Snakefile`
* [ ] `input:` and `output:` file paths in the rules can be chosen arbitrarily
* [ ] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`)
* [ ] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to 
* [ ] the `meta.yaml` contains a link to the documentation of the respective tool or command under `url:`
* [ ] conda environments use a minimal amount of channels and packages, in recommended ordering

2024-11-22 07:29 UTC, johanneskoester commented on bio/vg/giraffe/test/Snakefile
> +        minimizer=f"resources/genome.min",
```suggestion
        graph="resources/genome.giraffe.gbz",
        dist="resources/genome.dist",
        minimizer="resources/genome.min",
```

2024-11-22 07:33 UTC, johanneskoester requested changes

2024-11-22 07:34 UTC, johanneskoester commented on bio/vg/giraffe/test/Snakefile
> +        sort_extra="",  # Extra args for samtools/picard.
No, this is overkill.

2024-11-22 07:47 UTC, FelixMoelder commented on bio/vg/giraffe/wrapper.py
> +    input_cmd += f"-m {minimizer}"
Yes, depending on what kind of graph is passed the missing files will be created on the fly.
If we do not want to do this we should make the output of `vg autoindex` the mandatory input.

2024-11-22 07:51 UTC, FelixMoelder commented on bio/vg/giraffe/test/Snakefile
> +        minimizer=f"resources/genome.min",
If we use a multiext index we need to perform a check if all required files are part of that index.
Further we would need to identify each file to assign it to its corresponding parameter.
This will be easier in the current implementation.

2024-11-27 08:55 UTC, johanneskoester approved these changes

2024-11-27 08:56 UTC, merged