Update BUSCO to v5.1.2
snakemake/snakemake-wrappers pull request #338
Opened 2021-04-16 08:46 UTC by nikostr

This updates BUSCO from v5.0.0 to v5.1.2, and resolves issues with the old wrapper. Since the BUSCO output structure has been updated (since v4?), the old wrapper no longer works.

An improvement to the wrapper is an optional `download_path` parameter, allowing the user to specify a download path for BUSCO, e.g  in the `resources` directory.

I have not yet tested how this performs when multiple first-time runs are initiated. There may be issues if the same download path is used for all of them.

2021-04-19 15:47 UTC, jafors requested changes
Thanks a bunch. I made a few comments below.

2021-04-19 15:47 UTC, jafors commented on bio/busco/wrapper.py
> +        + " {extra} {log}"
```suggestion
        "--cpu {snakemake.threads} --mode {mode} --lineage {lineage} "
        "{download_path} "
        "{extra} {log}"
```

You can use `{download_path}` directly in the command string just as `{mode}` or `{lineage}`.

2021-04-19 15:47 UTC, jafors commented on bio/busco/wrapper.py
> +outdir = snakemake.output[0]
If I read the busco manual correctly, they do not advice to give a path here, just a `prefix` name for output folders and files. The  top-level  path leading to the results directory needs to be given by `--out_path`.
So if I want my results to be in sth. like `results/busco/sample`, I would need to call busco with `--out sample --out_path results/busco`.
Am I correct here? If so, you should think about how to parse the snakemake output into those two params, maybe using `os.path`.

2021-04-19 15:47 UTC, jafors commented on bio/busco/wrapper.py
> +    shell("cp -r {tmp_dir} {outdir}")
I think this is not necessary if the output options are set correctly (see above).

2021-04-20 07:05 UTC, nikostr commented on bio/busco/wrapper.py
> +outdir = snakemake.output[0]
Good catch! This is resolved by https://github.com/snakemake/snakemake-wrappers/pull/338/commits/f9a582a7d3ef218ab5a63fa4fdfe533c99b028f9. Much neater solution.

2021-04-20 07:08 UTC, nikostr commented
While I was at it I took the liberty of renaming `lineage_path` to `lineage`, as it is not a path that is being given there.

2021-05-03 13:38 UTC, jafors approved these changes

2021-05-03 13:38 UTC, merged