Added CollectRnaSeqMetrics wrapper.
snakemake/snakemake-wrappers pull request #359
Opened 2021-05-13 21:45 UTC by brcopeland

2021-05-27 09:50 UTC, jafors requested changes
Thanks a bunch! Small comments below.

2021-05-27 09:50 UTC, jafors commented on bio/picard/collectrnaseqmetrics/wrapper.py
> +extra = snakemake.params.get("extra", "")
If you want to treat `STRAND` as a specific parameter, please add an example with description in the example Snakefile. It is easier for the user to understand where to set this info without having to look into the wrapper script!
It might also be nice to always add the `extra` field to `params`, maybe even with some example flags.

2021-05-27 09:50 UTC, jafors commented on bio/picard/collectrnaseqmetrics/test/Snakefile
> +        refflat = "annotation.refFlat"
```suggestion
        bam="mapped/a.bam",
        refflat="annotation.refFlat"
```
As mentioned in other wrappers, `snakefmt` is your friend regarding these small cosmetic issues. ;)

2021-05-27 17:15 UTC, brcopeland commented
The failed test doesn't appear to be related to be related to this wrapper (some conda issue?).  I'm not clear on how to resolve that.

2021-05-28 07:35 UTC, jafors approved these changes

2021-05-28 10:53 UTC, merged