Added qualimap rnaseq wrapper.
snakemake/snakemake-wrappers pull request #360
Opened 2021-05-13 23:18 UTC by brcopeland

2021-05-25 23:18 UTC, brcopeland commented
Just to clarify the change made, the `qualimap` wrapper that runs the java program has a parameter, `--memory-size`, that like you'd expect passes this information onto java.  On the other hand, it does not have any option to modify the java temp directory except through putting it in the environment variable `JAVA_OPTS`, and hence the reason for utilizing that while ignoring `--memory-size`.

2021-05-27 09:45 UTC, jafors requested changes

2021-05-27 09:45 UTC, jafors commented on bio/qualimap/rnaseq/test/Snakefile
> +        gtf = "annotation.gtf"
```suggestion
        bam="mapped/a.bam",
        gtf="annotation.gtf"
```
If you format your Snakefiles with `snakefmt`, those things should be easy to catch. ;)

2021-05-27 09:45 UTC, jafors commented on bio/qualimap/rnaseq/test/Snakefile
> +        gtf = "annotation.gtf"
Also, it is always good to add some description for the `input`/`output`/`params` sections in the form of comments in the example Snakefile, even if they seem self-explanatory.

2021-05-27 15:58 UTC, brcopeland commented on bio/qualimap/rnaseq/test/Snakefile
> +        gtf = "annotation.gtf"
I've done that now.  I haven't heard of `snakefmt` previously, I'll take a look.

2021-05-31 13:33 UTC, jafors approved these changes
Thanks!

2021-05-31 13:47 UTC, merged