Liftoff
snakemake/snakemake-wrappers pull request #377
Opened 2021-06-11 09:29 UTC by tdido

### Description

Adding wrapper for liftoff (https://github.com/agshumate/Liftoff/tree/master/liftoff)

### QC

For all wrappers added by this PR, I made sure that

* [ x ] there is a test case which covers any introduced changes,
* [ x ] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [ x ] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [ x ] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [ x ] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [ x ] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [ x ] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [ x ] `Snakefile`s pass the linting (`snakemake --lint`),
* [ x ] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [ x ] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2021-06-14 10:57 UTC, jafors requested changes
Thanks for this addition! Just a few comments.

2021-06-14 10:57 UTC, jafors commented on bio/liftoff/test/Snakefile
> +        tgt = "{ref}.fasta.gz",
This seems to be an unlucky choice for this example Snakefile, as both reference and target fasta are identical here (`{ref}` evaluates to the same wildcard). If you want to use wildcards, use `{ref}` and `{target}` or something like this.

Also, please format the Snakefile using `snakefmt` to get rid of the spaces around the `=` etc.

2021-06-14 10:57 UTC, jafors commented on bio/liftoff/environment.yaml
> +  - liftoff == 1.6.*
```suggestion
  - liftoff =1.6
```

2021-06-14 11:57 UTC, tdido commented on bio/liftoff/environment.yaml
> +  - liftoff == 1.6.*
Thanks for the review! Changes applied.

2021-06-16 09:13 UTC, jafors approved these changes
Thanks for the changes! Looks good.

2021-06-16 09:13 UTC, merged