Add MLST wrapper
snakemake/snakemake-wrappers pull request #378
Opened 2021-06-16 06:09 UTC by maxlcummins

### Description

Add a wrapper script for MLST

### QC

For all wrappers added by this PR, I made sure that

* [x] there is a test case which covers any introduced changes,
* [x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [x] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [x] `Snakefile`s pass the linting (`snakemake --lint`),
* [x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2021-06-21 03:18 UTC, maxlcummins commented
Hello, having looked at the log I am unsure of what is causing the check above to fail. Any ideas of how I can resolve this issue please?

2021-06-22 00:03 UTC, maxlcummins commented
Hi there @jafors, is there any chance you can please give me a hand with this one when you are free?

2021-06-22 09:41 UTC, jafors requested changes
Hey, this tests are passing now, you just ran into some connection problems by github, I guess.
Try to clean the wrapper following the points I made on your last entry, especially reduce the `environment.yaml`. ;)

2021-06-23 05:13 UTC, maxlcummins commented
I typically export my environments from conda using `conda env export` which adds in all the extras - I didn't realise you could provide such a succinct yaml until recently thanks to your reviews. Thanks!

2021-06-23 06:04 UTC, jafors requested changes
Sure, no problem. Some suggestions similar to the last wrapper.

2021-06-23 06:04 UTC, jafors commented on bio/mlst/test/Snakefile
> +        #"https://raw.githubusercontent.com/maxlcummins/snakemake-wrappers/mlst/bio/mlst/wrapper.py"
```suggestion
        "master/bio/mlst"
```

2021-06-23 06:27 UTC, maxlcummins commented
Cheers, the next wrapper I submit will have log files and environment files changed as per your requests :)

2021-06-23 08:14 UTC, jafors commented on bio/mlst/wrapper.py
> +    "{log}"
```suggestion
    " {log}"
```
I forgot the space in my suggestion ;)

2021-06-23 08:15 UTC, jafors approved these changes

2021-06-23 08:31 UTC, merged