Add seqtk mergepe and improve docs
snakemake/snakemake-wrappers pull request #380
Opened 2021-06-18 03:26 UTC by mbhall88

### Description

#### Added

- Wrapper for `seqtk mergepe`
- Params section for wrapper docs
- Docs on what fields are available for use in the `meta.yaml` - with an example. I always have to look this up so thought it would be useful to add it to the docs
- URL field for wrapper docs (happy to remove if this isn't desirable, but it makes it more explicit that we want people to link to tool docs)
- Formatting and linting instructions in the contributing docs

#### Changed

- Moved contributing docs to a separate page

#### Removed

- Some log files that had been committed with the seqtk subsample wrappers

### QC

For all wrappers added by this PR, I made sure that

* [x] there is a test case which covers any introduced changes,
* [x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [ ] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071)

>  I would usually opt for pinning the major and minor version. This way, users will get the newest security patches and bug fixes whenever they create an environment, while nothing should change in a backward incompatible way

I appreciate this may not be up for debate, in which case I'm ok to change the version, but pinning the major version only is also backward-compatible and will give all of the latest patches and fixes...

* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [x] `Snakefile`s pass the linting (`snakemake --lint`),
* [x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2021-06-18 03:34 UTC, mbhall88 commented
Looks like `test_star_align` failed, but everything else passed... Is that fine or do you want me to rerun the build?

2021-06-24 07:46 UTC, jafors commented
Thanks for the work. I'm a fan of the additions and restructurings in the docs.
I'd ask @johanneskoester and @dlaehnemann  about their thoughts on this, but I like it. :)

2021-06-24 08:08 UTC, johanneskoester requested changes
Thanks a lot! The extension of the docs looks great!! I have just a few comments below.

2021-06-24 08:08 UTC, johanneskoester commented on docs/contributing.rst
> +we recommend adding your test case to the start of the list in ``test.py``, so
This is not necessary, because you can specifically target the test with test.py -k <testname>. Can you change these instructions accordingly?

2021-06-24 08:08 UTC, johanneskoester commented on docs/contributing.rst
> +  conda create -n test-snakemake-wrappers snakemake pytest conda snakefmt black
It would be better to use mamba instead of conda in these commands.

2021-06-24 10:00 UTC, dlaehnemann requested changes
Thanks a bunch, I very much appreciate the updates to the docs. This restructuring is a very good idea. I used the opportunity to also check for consistency with our [recently added PR template](https://github.com/snakemake/snakemake-wrappers/blob/a2a09b978b8c15988f7182cffa318b4a239a942a/.github/pull_request_template.md). So please excuse the deluge of comments and suggestions.

Regarding version pinning, I guess this is up for debate. Maybe we should debate this on Stackoverflow and adjust the wording there, if we agree to change the recommendations?

2021-06-24 10:00 UTC, dlaehnemann commented on bio/seqtk/mergepe/meta.yaml
> +  - paired fastq files - can be compressed.
I guess this `compressed` here means gzipped, right? So maybe:
```suggestion
  - paired fastq files - can be compressed in gzip format (``*.gz``).
```

2021-06-24 10:00 UTC, dlaehnemann commented on bio/seqtk/mergepe/environment.yaml
> +  - pigz =2
As you were saying, this should also keep the dependencies backwards compatible. I guess the idea of also pinning a minor version is simply a more conservative approach, as people do not necessarily follow semantic versioning conventions to the dot and sometimes behavior does change between minor versions, which might break a wrapper. But only pinning a major version reduces the maintenance burden. So I'm torn. Maybe @jafors @johanneskoester have opinions?

2021-06-24 10:00 UTC, dlaehnemann commented on bio/seqtk/mergepe/wrapper.py
> +    "| pigz -{compress_lvl} -c -p {snakemake.threads}) > {snakemake.output} {log}"
Can we make the compression part of the command optional, depending on whether the output has `.gz` as the file extension or not? I guess this also makes the `compress_lvl` optional and requires to sanity check that it is not present if `.gz` is not specified, as this indicates a mis-configuration?

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +``meta.yaml`` file
Add this for linking:

```suggestion
.. _meta:

``meta.yaml`` file
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +* provide a ``meta.yaml`` with name, description and author(s) of the wrapper
```suggestion
* provide a ``meta.yaml`` that describes the wrapper (see the `meta.yaml documentation below <meta>`_)
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +Formatting
Add this for linking:
```suggestion
.. _formatting:

Formatting
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +  using 4 spaces for indentation.
```suggestion
* ensure consistent `formatting`_ of Python files and `linting`_ of Snakefiles
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +Linting
Add this for linking:
```suggestion
.. _linting:

Linting
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +* provide a minimal test case in a subfolder called ``test``, with an example
Add in the `wrapper.*` files here for a more complete description of requirements:
```suggestion
* add a `wrapper.py` or `wrapper.R` file that can deal with arbitrary `input:` and `output:` paths,
  handles all `params:` and executes the actual software call
* provide a minimal test case in a subfolder called ``test``, with an example
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +  ``Snakefile`` that shows how to use the wrapper, some minimal testing data
Add info that is in PR template:
```suggestion
  ``Snakefile`` that shows how to use the wrapper (rule names should be descriptive and written
  in `snake_case <https://en.wikipedia.org/wiki/Snake_case>`_), some minimal testing data
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +* provide an ``environment.yaml`` which lists all required software packages (the
Add info from PR template:
```suggestion
* provide an ``environment.yaml`` which lists all required software packages and follows
  `the respective best practices <https://stackoverflow.com/a/64594513/2352071>`_  (the
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +The following fields are available to use in the wrapper ``meta.yaml`` file:
```suggestion
The following fields are available to use in the wrapper ``meta.yaml`` file. All, except
those marked optional, should be filled:
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +* **notes**: Anything of note that does not fit into the scope of the other fields.
```suggestion
* **params** (only applies when params are used): A `mapping`_ of parameters that can be used in the wrapper's ``params`` directive.
* **notes** (optional): Anything of note that does not fit into the scope of the other fields.
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +we recommend adding your test case to the start of the list in ``test.py``, so
Yeah, I didn't know this when I wrote these instructions. I'll make a suggestions for the wording.

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +environment with the necessary dependencies and activate it::
```suggestion
If you want to debug your contribution locally (before creating a pull request), you can
install all dependencies with mamba. `Install miniconda with the channels as described for
bioconda <https://bioconda.github.io/#using-bioconda>`_ and set up an
environment with the necessary dependencies and activate it::
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +  conda create -n test-snakemake-wrappers snakemake pytest conda snakefmt black
```suggestion
  mamba create -n test-snakemake-wrappers snakemake pytest conda snakefmt black
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +  pytest test.py -v
```suggestion
Afterwards, from the main directory of the repo, you can run your the tests by specifying
an expression that matches the names of your tests via  the ``-k`` option of ``pytest`` with::

  pytest test.py -v -k your_test1
```

2021-06-24 10:00 UTC, dlaehnemann commented on docs/contributing.rst
> +  conda create -n test-snakemake-wrapper-docs sphinx sphinx_rtd_theme pyyaml sphinx-copybutton
```suggestion
  mamba create -n test-snakemake-wrapper-docs sphinx sphinx_rtd_theme pyyaml sphinx-copybutton
```

2021-06-25 04:33 UTC, mbhall88 commented on bio/seqtk/mergepe/wrapper.py
> +    "| pigz -{compress_lvl} -c -p {snakemake.threads}) > {snakemake.output} {log}"
As I mentioned in the meta docs, if `compress_lvl=0` then no compression is done. I'm not a fan of checking file extensions against compression level etc. Seems like a little too much hand-holding no? It also forces people into using a `.gz` extension. Although this is without a doubt a common convention, it isn't mandatory for a file to be compressed.

2021-06-25 04:59 UTC, mbhall88 commented on bio/seqtk/mergepe/environment.yaml
> +  - pigz =2
Happy to discuss.

My main reason for only wanting to pin the major version was I find I quite regularly want a minor version higher than the one on the wrapper and it seems like a lot of maintenance burden (as you say) to put in a PR every time there is a minor version bump.  
Sure there will be times when people aren't following semver and this leads to backwards incompatibilities, but that is more on the tool developers/maintainers, not us, and can be easily worked around by pinning the minor version in those cases.

2021-06-25 07:01 UTC, johanneskoester commented on bio/seqtk/mergepe/environment.yaml
> +  - pigz =2
I would prefer to stick to pinning the minor version here. Otherwise, we might loose reproducibility (the same workflow deployed twice might use two different minor versions, which can make a difference in the results. For patch versions thats more unlikely and I am willing to take that risk, but not for minor versions. I agree on the maintenance burden, but for the sake of reproducibility, let us rather strive for another solution: we extend (e.g.) snakedeploy or any other tool for which it makes sense with functionality to update a given conda environment to the latest minor versions. This should be fairly simple to implement:

1. Extract package names and channels from the env.
2. Run `mamba create --dry-run --json -c <channels> <packages>`.
3. Extract the versions from the packages in the json that also occur in the original env.
4. Rewrite the env with minor version pinnings derived from the extracted versions.

I can try to write that ASAP, unless anybody else of you wants to do that.

2021-06-25 07:04 UTC, johanneskoester commented on bio/seqtk/mergepe/wrapper.py
> +    "| pigz -{compress_lvl} -c -p {snakemake.threads}) > {snakemake.output} {log}"
I think it should be fine to only support compression here. Outputting uncompressed data in this case seems like an irrelevant corner case to me. In the end, wrappers should support the relevant use cases (which should mostly be driven by the people contributing here). We don't need to use too much of our time on things that we ourselves won't use.

2021-06-25 09:15 UTC, dlaehnemann commented on bio/seqtk/mergepe/wrapper.py
> +    "| pigz -{compress_lvl} -c -p {snakemake.threads}) > {snakemake.output} {log}"
OK, both your arguments convince me!

2021-06-25 09:19 UTC, dlaehnemann commented on bio/seqtk/mergepe/environment.yaml
> +  - pigz =2
Would you then use this for automatic minor version update PRs of the snakemake wrappers here, or for updating the minor versions of tools in environments used by a wrapper in a workflow? For the latter, this sounds like a source of confusion to me, but I think I simply don't fully understand yet, where your suggestion is supposed to fit in.

2021-06-25 09:34 UTC, dlaehnemann commented
@mbhall88 There are still a bunch of points from my review that are open. I had to manually click on `8 hidden conversations, Load more` or change over to the `Files changed` tab, so maybe you didn't see them in the Conversation tab of the PR?

2021-06-26 05:33 UTC, mbhall88 commented on bio/seqtk/mergepe/environment.yaml
> +  - pigz =2
> I would prefer to stick to pinning the minor version here. Otherwise, we might loose reproducibility (the same workflow deployed twice might use two different minor versions, which can make a difference in the results

This is indeed true and I am now convinced that minor version pinning is best.

I'm happy to just pin the minor versions in this PR. Don't worry about rushing through any new functionality @johanneskoester. I'm also not sure I quite follow the extension you are suggesting. Maybe start a new issue for it?

2021-06-26 05:53 UTC, mbhall88 commented
> @mbhall88 There are still a bunch of points from my review that are open. I had to manually click on `8 hidden conversations, Load more` or change over to the `Files changed` tab, so maybe you didn't see them in the Conversation tab of the PR?

Ah very sorry @dlaehnemann. I've added those suggestions.

I think it might also be good to add a more thorough part of the docs describing how to best write a `wrapper.py`. I would do it, but I need to do some PhD.

2021-06-28 07:16 UTC, johanneskoester commented on bio/seqtk/mergepe/environment.yaml
> +  - pigz =2
Good idea, here we go:
https://github.com/snakemake/snakedeploy/issues/17

@dlaehnemann, this should hopefully also answer your question.

2021-06-28 07:16 UTC, johanneskoester commented on bio/seqtk/mergepe/environment.yaml
> +  - pigz =2
Let us move further discussion to that issue.

2021-06-28 07:17 UTC, johanneskoester commented
> > @mbhall88 There are still a bunch of points from my review that are open. I had to manually click on `8 hidden conversations, Load more` or change over to the `Files changed` tab, so maybe you didn't see them in the Conversation tab of the PR?
> 
> Ah very sorry @dlaehnemann. I've added those suggestions.
> 
> I think it might also be good to add a more thorough part of the docs describing how to best write a `wrapper.py`. I would do it, but I need to do some PhD.

Thanks a lot for all your contributions although writing a thesis. This is highly appreciated!

2021-06-28 07:17 UTC, johanneskoester approved these changes

2021-06-28 09:03 UTC, dlaehnemann approved these changes
@mbhall88 You're definitely right, that a detailed description of how to write a `wrapper.py` and `wrapper.R` would be great. But you're even more right to focus on your PhD. I documented that need over in the new issue #385.

Otherwise, this is good to go. I just have one suggestion for adding a sentence, but feel free to ignore that one, if you think this is not useful.

2021-06-28 22:52 UTC, mbhall88 commented on docs/contributing.rst
> +The pull request will be reviewed and included as fast as possible.
I've updated that suggestion a little. If the change is ok with you feel free to commit it and then merge this :+1:

2021-06-29 08:14 UTC, merged

2021-06-29 08:44 UTC, dlaehnemann commented
:tada: