Add metaspades assembler
snakemake/snakemake-wrappers pull request #386
Opened 2021-06-30 15:14 UTC by SilasK

### Description

Add metaspades assembler

### QC

For all wrappers added by this PR, I made sure that

* [ ] there is a test case which covers any introduced changes,
* [ ] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [ ] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [ ] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [ ] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [ ] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [ ] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [ ] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [ ] `Snakefile`s pass the linting (`snakemake --lint`),
* [ ] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [ ] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2021-06-30 15:19 UTC, SilasK commented
@alienzj @asl
For your information. I create this snakemake wrapper for metaspades. Maybe the other spades later.

2021-06-30 19:00 UTC, asl commented on bio/spades/metaspades/wrapper.py
> +        " --threads {threads} "
You need --continue here

2021-07-01 00:18 UTC, alienzj commented on bio/spades/metaspades/wrapper.py
> +        " --threads {threads} "
Can we specify `--continue` and `--threads`, `--memory` at the same time?

2021-07-01 04:48 UTC, asl commented on bio/spades/metaspades/wrapper.py
> +        " --threads {threads} "
No, `--continue` uses the same amount of memory / CPU threads. If you need to change this, then you'd need to use `--restart-from last`.

2021-07-01 11:22 UTC, SilasK commented on bio/spades/metaspades/meta.yaml
> +  Metagenome assembly uses a lot of computational resources. Spades is told to restart from a previous checkpont if the file `params.txt` exist in the output directory. In this way one can use snakem
> I read somewhere that spades doesn't scale very well to many cores therefore I suggest to keep the threads around 10.
@asl Is this still true?

2021-07-23 14:06 UTC, SilasK commented
@johanneskoester @fgvieira Could you please review my PR?

2021-07-23 14:09 UTC, asl commented on bio/spades/metaspades/environment.yaml
> +  - spades ==3.15
Not sure if this is a correct specification. As it prohibits bug-fix versions, say, 3.15.2 or 3.15.3 that will be released soon

2021-07-23 14:11 UTC, asl commented on bio/spades/metaspades/meta.yaml
> +  Metagenome assembly uses a lot of computational resources. Spades is told to restart from a previous checkpont if the file `params.txt` exist in the output directory. In this way one can use snakem
No, it is not

2021-07-23 14:12 UTC, asl commented on bio/spades/metaspades/wrapper.py
> +        " --memory {resources.mem_mb}000 "
memory is in gigabytes, so you need to divide

2021-07-23 14:12 UTC, asl commented on bio/spades/metaspades/wrapper.py
> +        " --memory {resources.mem_mb}000 "
ditto

2021-07-23 20:26 UTC, SilasK commented on bio/spades/metaspades/environment.yaml
> +  - spades ==3.15
It is valuable for both
https://stackoverflow.com/questions/64594146/best-practices-for-bioconda-versions-in-snakemake-wrappers/64594513#64594513

2021-07-25 09:58 UTC, asl commented on bio/spades/metaspades/environment.yaml
> +  - spades ==3.15
In fact, I'm slightly disagreeing with what is written. The issue is that all these pipelines and wrappers are rarely got updated. As a result the users still use old outdated versions of the tools (we're seeing 3-4-5-old versions with known issues still in use and users are unable to use newer version simply because the pipeline has the version hardcoded somewhere). Certainly, pinning of the version ensures that the wrapper will always work, so, it's all about pros and cons here.

From the SPAdes side we work hard on ensuring backward compatibility and given the extremely simplicity of the wrapper, may I suggest that the version specifier to be >= 3.15? :)

2021-07-25 10:00 UTC, asl commented on bio/spades/metaspades/wrapper.py
> +if hasattr(snakemake.params, "output_dir"):
Please, please save the assembly graph as well :)

2021-07-26 10:02 UTC, SilasK commented on bio/spades/metaspades/environment.yaml
> +  - spades ==3.15
I adapted the version. 
I agree spades is very good compatible between the versions

2021-07-27 01:10 UTC, alienzj approved these changes

2021-08-03 11:52 UTC, jafors requested changes
Hi and thanks for the addition. Some nice ideas! Yet you are lacking a testcase in the `test.py` and there are some other things that would have probably arisen in a test run.

2021-08-03 11:52 UTC, jafors commented on bio/spades/metaspades/test/Snakefile
> +        reads=["test_reads/sample1_R1.fastq.gz", "test_reads/ample1_R2.fastq.gz"],
```suggestion
        reads=["test_reads/sample1_R1.fastq.gz", "test_reads/sample1_R2.fastq.gz"],
```
Typo!

2021-08-03 11:52 UTC, jafors commented on bio/spades/metaspades/test/Snakefile
> +        "master/bio/bwa/aln"
This is likely a relict from the wrapper you used as a template. If you add a testcase, this should throw an error.

2021-08-03 11:52 UTC, jafors commented on bio/spades/metaspades/test/Snakefile
> +        " tar -xzf test_reads.tar.gz >> {log} 2>&1"
You are missing an `&&` between the `wget` and `tar`. Generally, it's not a bad idea to download the test data instead of adding it to the repo directly, but make sure that this is called correctly during your testcase.

2021-08-03 11:52 UTC, jafors commented on bio/spades/metaspades/wrapper.py
> +kmers = snakemake.params.get("k", "'auto'")
There is a default value for `-k` in spades, right? Why not use this value if `k` is not given in the params?

2021-08-03 11:52 UTC, jafors commented on bio/spades/metaspades/test/Snakefile
> +        " tar -xzf test_reads.tar.gz >> {log} 2>&1"
Also, the same typo as above.

2021-08-03 12:20 UTC, SilasK commented on bio/spades/metaspades/wrapper.py
> +kmers = snakemake.params.get("k", "'auto'")
'auto' is the default in spades, as far as I know.

2021-08-03 12:33 UTC, SilasK commented
Maybe it would be worth splitting up the test.py in per-repo test scripts and then run them all. 

Thank you for your comments @jafors. I made the modifications.

2021-08-03 12:56 UTC, jafors commented on bio/spades/metaspades/wrapper.py
> +kmers = snakemake.params.get("k", "'auto'")
Ah, ok. I am not really familiar with the tool, probably read that wrong on the docs page.

2021-08-03 15:34 UTC, SilasK commented
@jafors Could you approve the review? and run the tests. From my side, I cannot proceed. 

Is there a way to test the wrapper locally?

2021-08-04 09:45 UTC, jafors commented
@SilasK , you can test locally following those instructions: https://snakemake-wrappers.readthedocs.io/en/stable/contributing.html#testing-locally

2021-08-05 10:22 UTC, SilasK commented
@jafors I successfully tested locally. GitHub tells me that you requested changes that are not yet approved. It links to the https://github.com/snakemake/snakemake-wrappers/pull/386#pullrequestreview-721092587

Could you approve this PR so it could be merged?

2021-08-11 07:55 UTC, jafors approved these changes

2021-08-11 07:55 UTC, merged