Added wrapper for verifybamid2.
snakemake/snakemake-wrappers pull request #401
Opened 2021-09-09 21:03 UTC by brcopeland

### Description
This provides a wrapper for the tool `verifybamid2` which can be used to estimate intra-species contamination in a BAM file.

### QC

For all wrappers added by this PR, I made sure that

* [ x] there is a test case which covers any introduced changes,
* [ x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [x ] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [x ] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [ x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [ x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [ x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [ x] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* [x ] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [ x] `Snakefile`s pass the linting (`snakemake --lint`),
* [ x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x ] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2021-09-30 07:24 UTC, johanneskoester requested changes

2021-09-30 07:24 UTC, johanneskoester commented on bio/verifybamid/verifybamid2/test/Snakefile
> +        svd_prefix="ref.vcf",
This should be an optional input file then, not a parameter.

2021-09-30 07:24 UTC, johanneskoester commented
Thanks a lot, nice work! Just one comment above.

2021-09-30 16:36 UTC, brcopeland commented on bio/verifybamid/verifybamid2/test/Snakefile
> +        svd_prefix="ref.vcf",
So the `svd_prefix` that is passed in to `verifybamid2` is not actually a file that exists, so that's why I didn't make it an input file.  I could change it to have as an input one of the files that do exist, strip off the file suffix, and pass that to `verifybamid2` if you would prefer.

2021-11-09 08:31 UTC, johanneskoester commented on bio/verifybamid/verifybamid2/test/Snakefile
> +        svd_prefix="ref.vcf",
Mhm, would it be possible to specify all needed files under that prefix explicitly? E.g. using [multiext](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=multiext#the-multiext-function)?

2021-11-09 18:54 UTC, brcopeland commented on bio/verifybamid/verifybamid2/test/Snakefile
> +        svd_prefix="ref.vcf",
I changed `params.svd_prefix` to `input.svd_mu`.  This file name would be the same as the other with the suffix `.mu` appended.  `verifybamid2` requires other files with suffixes `.bed`, `.UD`, and `.V` to exist so the wrapper checks that.

Please note that the wrapper looks explicitly for `input.svd_mu` and not for the others as far as specified arguments go.  I just thought that approach would be simpler to work with.

2022-01-17 10:26 UTC, johanneskoester approved these changes

2022-01-17 10:26 UTC, merged