Changed handling of temp directory to snakemake resource
snakemake/snakemake-wrappers pull request #411
Opened 2021-10-22 14:31 UTC by fgvieira

### Description

Use `snakemake` `tmpdir` resource, instead of defining `--tmp-dir` in the rule

### QC

For all wrappers added by this PR, I made sure that

* [x] there is a test case which covers any introduced changes,
* [x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [x] either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* [x] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [x] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [x] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [x] `Snakefile`s pass the linting (`snakemake --lint`),
* [x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2021-11-09 08:23 UTC, johanneskoester requested changes

2021-11-09 08:23 UTC, johanneskoester commented on bio/gatk/genotypegvcfs/test/Snakefile
> +        tmpdir="tmp/"
No need to specify this here directly, this would just encourage anti-patterns. Rather, this should be handled by --default-resources, see [here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=tmpdir#standard-resources).

2021-11-09 08:32 UTC, fgvieira commented on bio/gatk/genotypegvcfs/test/Snakefile
> +        tmpdir="tmp/"
Not sure what you mean by 
Ok, so I'll remove the explicit definition of `tmpdir` from here.

2021-11-11 12:31 UTC, johanneskoester approved these changes

2021-11-11 12:31 UTC, merged