Wrapper for Manta SV caller
snakemake/snakemake-wrappers pull request #415
Opened 2021-11-04 12:01 UTC by fgvieira

### Description

### QC

For all wrappers added by this PR, I made sure that

* [x] there is a test case which covers any introduced changes,
* [x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [x] either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* [x] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [x] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [ ] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [x] `Snakefile`s pass the linting (`snakemake --lint`),
* [x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2021-11-04 12:08 UTC, fgvieira commented
Not sure how to deal with the temp files, since `manta` creates a folder with everything (temp files included).
We could set the workdir to a temp folder (with python `tempfile`) and move the result files to their final destination at the end, but this would make it impossible to access all the logs and intermediate files `manta` creates (in case the user wants them).

2021-11-09 08:16 UTC, johanneskoester requested changes
Nice work, just one thing.

2021-11-09 08:16 UTC, johanneskoester commented on bio/manta/test/Snakefile
> +        outdir=temp(directory("temp/")),
Maybe leave a comment here explaining what this directory will contain.

2021-11-09 08:26 UTC, fgvieira commented on bio/manta/test/Snakefile
> +        outdir=temp(directory("temp/")),
But should we leave that directory for the user to define (and set as temp), or should we internally define it as `tmpdir` with python?

2021-11-11 12:27 UTC, johanneskoester commented on bio/manta/test/Snakefile
> +        outdir=temp(directory("temp/")),
Depends on whether you think the directory will contain useful output. The wrapper could alternatively also copy out certain files of it upon definition of them as log files or output files. That would probably be the nicer way.

2021-11-29 12:17 UTC, fgvieira commented on bio/manta/test/Snakefile
> +        outdir=temp(directory("temp/")),
Ok, in the end I think it is cleaner to just use `tempfile` and copy out important files.
If anyone needs any of the other files, we can just change the wrapper to also copy those files.

2022-01-17 10:12 UTC, johanneskoester requested changes

2022-01-17 10:12 UTC, johanneskoester commented on bio/manta/wrapper.py
> +            )
This looks quite redundant to me. Can you turn it into a function that is just called 3 times?

2022-01-17 15:12 UTC, fgvieira commented on bio/manta/wrapper.py
> +            )
You're right... it can definitely be made cleaner. :)

2022-01-18 13:03 UTC, johanneskoester requested changes

2022-01-18 13:03 UTC, johanneskoester commented on bio/manta/wrapper.py
> +    idx_final = snakemake.output.get("idx", "")
No need to add "" as default case here and below. If you omit that, it will return None, which should be fine for the function as well.

2022-01-18 14:50 UTC, fgvieira commented on bio/manta/wrapper.py
> +    idx_final = snakemake.output.get("idx", "")
Sure.

2022-01-26 14:42 UTC, johanneskoester approved these changes

2022-01-26 14:42 UTC, merged