explicitly specify bwa index in bwa samxe
snakemake/snakemake-wrappers pull request #448
Opened 2022-01-27 09:13 UTC by fgvieira

### Description

Following #232, doing the same for the `smaxe` wrapper. 

### QC

For all wrappers added by this PR, I made sure that

* [x] there is a test case which covers any introduced changes,
* [x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [x] either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* [x] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [x] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [x] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [x] `Snakefile`s pass the linting (`snakemake --lint`),
* [x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2022-01-27 09:17 UTC, fgvieira commented
@johanneskoester this one has the same problem as #446, so it seems it is an issue with `snakemake`. Can you take a look, when you have time?

thanks,

2022-02-07 08:04 UTC, johanneskoester requested changes

2022-02-07 08:04 UTC, johanneskoester commented on bio/bwa/samxe/test/Snakefile_samtools
> +        # Index can be a list of (all) files created by bwa, or one of them
While one of them would suffice in the local case, you need all in case there is no shared file system (i.e. in the cloud). Hence, it is best practice to have all of them mentioned here.

2022-02-07 08:13 UTC, fgvieira commented on bio/bwa/samxe/test/Snakefile_samtools
> +        # Index can be a list of (all) files created by bwa, or one of them
It is just that a similar comment was added on the other `bwa` wrappers recently. But just removed it and also in the other wrappers.

2022-02-21 08:44 UTC, johanneskoester approved these changes

2022-02-21 08:44 UTC, merged