feat: Add wrapper for GATK DepthOfCoverage
snakemake/snakemake-wrappers pull request #494
Opened 2022-06-08 15:33 UTC by ljmesi

### Description

This PR adds a wrapper for GATK DepthOfCoverage tool.

### QC

For all wrappers added by this PR, I made sure that

* [x] there is a test case which covers any introduced changes,
* [x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [x] either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* [x] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [x] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [x] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [x] `Snakefile`s pass the linting (`snakemake --lint`),
* [x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2022-06-13 12:54 UTC, fgvieira commented on bio/gatk/depthofcoverage/meta.yaml
> +  * For more information see, https://gatk.broadinstitute.org/hc/en-us/articles/5358877443995-DepthOfCoverage-BETA-
```suggestion
url: https://gatk.broadinstitute.org/hc/en-us/articles/5358877443995-DepthOfCoverage-BETA-
authors:
  - Lauri Mesilaakso
input:
  - one or more bam files to be analyzed for coverage statistics
  - one or more genomic intervals over which to operate
  - reference genome
output:
  - base file location to which to write coverage summary information
notes: |
  * The `extra` param allows for additional program arguments.
```

2022-06-14 13:17 UTC, johanneskoester requested changes

2022-06-15 13:44 UTC, ljmesi commented on bio/gatk/depthofcoverage/meta.yaml
> +  - one or more bam files to be analyzed for coverage statistics
This is fixed now with commit [ca02aff](https://github.com/snakemake/snakemake-wrappers/pull/494/commits/ca02affbb006032227c7358b8bca86eb6229ecb7).

2022-06-17 12:04 UTC, fgvieira commented on bio/gatk/depthofcoverage/wrapper.py
> +out_basename = str(out_file.parent / out_file.stem)
@johanneskoester, I was thinking that it could be nice to have this feature (extract of basename from a set of output files) added to the `snakemake-wrapper-utils` as a function.

There are several wrappers that follow the same logic as here.

2022-06-26 08:18 UTC, fgvieira commented on bio/gatk/depthofcoverage/wrapper.py
> +out_basename = str(out_file.parent / out_file.stem)
or maybe just use `os`:
```
out_basename = os.path.commonprefix(snakemake.output).rstrip(".")
```

2022-06-29 11:47 UTC, Smeds commented on test.py
> +            "depth/a.sample_summary" "--use-conda",
```suggestion
            "depth/a.sample_summary",
            "--use-conda",
```

2022-06-30 13:26 UTC, ljmesi commented on bio/gatk/depthofcoverage/wrapper.py
> +out_basename = str(out_file.parent / out_file.stem)
Thanks for suggestion for simplification @fgvieira! I have now made the suggested changes.

2022-08-16 12:34 UTC, johanneskoester requested changes

2022-08-16 12:34 UTC, johanneskoester commented on bio/gatk/depthofcoverage/environment.yaml
> +  - defaults
```suggestion
  - conda-forge
  - bioconda
  - nodefaults
```

2022-08-16 12:34 UTC, johanneskoester commented on bio/gatk/depthofcoverage/environment.yaml
> +  - defaults
Reasoning: defaults channel is not needed anymore, excluding it makes conda/mamba faster. conda-forge has to come at higher priority than bioconda because bioconda has some old packages that have been moved to conda-forge.

2022-08-18 10:45 UTC, fgvieira approved these changes

2022-09-07 13:41 UTC, ljmesi commented
@johanneskoester Should there be done anything additional so that this PR can be merged?

2022-09-19 14:04 UTC, johanneskoester approved these changes

2022-09-19 14:04 UTC, merged