feat: BWA mem2 index - remove prefix parameter and determine prefix from output
snakemake/snakemake-wrappers pull request #515
Opened 2022-07-06 15:52 UTC by christopher-schroeder

### Description

Remove the param prefix and detect prefix by output

### QC

For all wrappers added by this PR, I made sure that

* [x] there is a test case which covers any introduced changes,
* [x] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [x] either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* [x] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [x] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [x] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [x] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [x] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [x] `Snakefile`s pass the linting (`snakemake --lint`),
* [x] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [x] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2022-07-08 09:22 UTC, tedil commented on bio/bwa-mem2/index/wrapper.py
> +prefix = "-p" + path.splitext(snakemake.output[0])[0]
`splitext` will only remove the very last extension, e.g. 
```python
splitext("genome.fasta.gz") == ("genome.fasta", ".gz")
splitext("genome.fasta") == ("genome", ".fasta")
```
Is this the desired behaviour?

2022-07-08 10:07 UTC, christopher-schroeder commented on bio/bwa-mem2/index/wrapper.py
> +prefix = "-p" + path.splitext(snakemake.output[0])[0]
The output[0] gets split, not the input. But you are right anyway, because there is an output file with suffix ".bwt.2bit.64". The case that that this file is the first declared output file is now covered.

2022-07-08 10:23 UTC, tedil approved these changes
LGTM!

2022-07-18 18:31 UTC, fgvieira commented
Wouldn't it be cleaner to infer the prefix with `os.path.commonprefix()`?

2022-07-19 09:18 UTC, fgvieira commented on bio/bwa-mem2/index/wrapper.py
> +shell(f"bwa-mem2 index -p {prefix} {snakemake.input[0]} {log}")
```suggestion
shell("bwa-mem2 index -p {prefix} {snakemake.input[0]} {log}")
```

2022-07-19 09:46 UTC, fgvieira commented
Like mentioned on issue #494, maybe we can define a function to infer the prefixes and add it to `snakemake-wrapper-utils`. Someting like:

```
def infer_prefix(files, suffixes, strict = True):
    prefixes = []
    suffixes = set(suffixes)
    
    for file in files:
        for suffix in suffixes:
            if file.endswith(suffix):
                prefixes.append(file[:-len(suffix)])

    if len(prefixes) != len(files) and strict:
        raise ValueError("All files must have a valid suffix.")
    if len(set(prefixes)) != 1:
        raise ValueError("All files must share common prefix.")

    return prefixes[0]
```

2022-08-16 13:15 UTC, johanneskoester requested changes
Nice work, some suggestions below. In general, I like the idea of @fgvieira to move the suffix handling code into snakemake-wrapper-utils, but to get things going I am fine with committing it here for now and moving it there later.

2022-08-16 13:15 UTC, johanneskoester commented on bio/bwa-mem2/index/wrapper.py
> +valid_suffixes = [".0123", ".amb", ".ann", ".bwt.2bit.64", ".pac"]
```suggestion
valid_suffixes = {".0123", ".amb", ".ann", ".bwt.2bit.64", ".pac"}
def get_valid_suffix(path):
    for suffix in valid_suffixes:
        if path.endswith(suffix):
            return suffix
```

2022-08-16 13:15 UTC, johanneskoester commented on bio/bwa-mem2/index/wrapper.py
> +    if not suffix in valid_suffixes:
```suggestion
    suffix = get_valid_suffix(s)
    if suffix is None:
```

2022-08-18 09:32 UTC, johanneskoester approved these changes

2022-08-18 09:32 UTC, merged