feat: add datavzrd wrapper
snakemake/snakemake-wrappers pull request #535
Opened 2022-08-12 06:05 UTC by FelixMoelder

### Description

This adds a wrapper for datavzrd

### QC

* [x] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

2022-08-12 07:49 UTC, fgvieira commented on utils/datavzrd/wrapper.py
> +shell("datavzrd {snakemake.input.config} --output {snakemake.output[0]} {log}")
Is `input.table` not used?

2022-08-12 07:50 UTC, fgvieira commented on utils/datavzrd/meta.yaml
> +authors:
```suggestion
url: https://github.com/koesterlab/datavzrd
authors:
```

2022-08-12 10:02 UTC, FelixMoelder commented on utils/datavzrd/wrapper.py
> +shell("datavzrd {snakemake.input.config} --output {snakemake.output[0]} {log}")
datavzrd only takes a config file as input without any option for extra parameters.
Therefore the only mandatory input field is `input.config`. Still, datavzrd utilizes tables and json-files defined within the config-file.
In the testcase I added `input.table` as an example as it appears reasonable to me defining supplementary files being processed by datavzrd.
I admit that this is not intuitive which is why I added a small description in the `meta.yaml`.
In general the wrapper is kind of a pseudo wrapper as it does not do more than calling `datavzrd` without any further preprocessing.

Also the report-directive appears to be unnecessary for a minimal example but datavzrd reports are often embedded into snakemake reports which is why this is also added to the testcase.

The reason for making it a wrapper is that datavzrd is required for several workflows and it at least provides us a template rule which can be customized with low effort.

2022-08-12 10:20 UTC, fgvieira commented on utils/datavzrd/wrapper.py
> +shell("datavzrd {snakemake.input.config} --output {snakemake.output[0]} {log}")
Is the config file pretty standard or are there a lot of options to tweak? Because it could also be generated by the wrapper itself, from user-specified parameters. It might be overkill, though...

2022-08-12 10:30 UTC, FelixMoelder commented on utils/datavzrd/wrapper.py
> +shell("datavzrd {snakemake.input.config} --output {snakemake.output[0]} {log}")
The config file is pretty custom and describes the layout of the final html-report.
In our current setup we also perform parsing of a template config file using `yte`.
Still it might be possible to add this to the wrapper as `yte` offers a python api.
@johanneskoester What's your opinion on that?

2022-08-15 11:01 UTC, johanneskoester commented on utils/datavzrd/wrapper.py
> +shell("datavzrd {snakemake.input.config} --output {snakemake.output[0]} {log}")
Automatic inference of the config file makes no sense here, because it really lives from the semantic added to it beyond just the file paths. Above the rule, there should however be a link to the section on template rendering, because most of the time people will do that when using this wrapper: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#template-rendering-integration

2022-08-16 14:19 UTC, johanneskoester requested changes
Some small suggestions below.

2022-08-16 14:19 UTC, johanneskoester commented on utils/datavzrd/environment.yaml
> +  - conda-forge
```suggestion
  - conda-forge
  - nodefaults
```

2022-08-16 14:19 UTC, johanneskoester commented on utils/datavzrd/meta.yaml
> +  within the configuration file are present.
```suggestion
  Any files specified in the configuration file have to be also specified as additional input files in the
  datavzrd rule.
```

2022-08-16 14:19 UTC, johanneskoester commented on utils/datavzrd/test/Snakefile
> +        # optional files required for rendering
```suggestion
        # optional files required for rendering the given config
```

2022-08-16 15:17 UTC, johanneskoester commented on utils/datavzrd/test/Snakefile
> +            subcategory="somatic variants",
```suggestion
            # see https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html
            # for additional options like caption, categories and labels
```

2022-08-18 06:41 UTC, johanneskoester approved these changes

2022-08-18 06:41 UTC, merged