feat: Merqury
snakemake/snakemake-wrappers pull request #540
Opened 2022-08-16 19:06 UTC by fgvieira

### Description

### QC

* [x] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

2022-08-23 07:31 UTC, johanneskoester requested changes

2022-08-23 07:31 UTC, johanneskoester commented on bio/merqury/test/Snakefile
> +        logs=directory("logs/haploid/"),
Is this really an output or rather should be put into log?

2022-08-23 07:31 UTC, johanneskoester commented on bio/merqury/wrapper.py
> +        shell("cat out.hapmers.blob.png > {snakemake.output.hapmers_png}")
Maybe use mv for all of these? That would be faster than cat and pipe.

2022-08-30 19:08 UTC, fgvieira commented on bio/merqury/wrapper.py
> +        shell("cat out.hapmers.blob.png > {snakemake.output.hapmers_png}")
I switched PNG output files to `mv`. As for the others, what if the user wants to pipe the outputs?

2022-08-30 19:15 UTC, fgvieira commented on bio/merqury/test/Snakefile
> +        logs=directory("logs/haploid/"),
This program is a bit of a mess... saves all outputs and logs to the `cwd`, and most output names are hard coded (that is why I recommend running it as a shadow rule). Among those, it creates a `log` folder with a couple of log files inside. I guess I could specify several log files... Do you think that would be cleaner?

2022-09-19 14:01 UTC, johanneskoester commented on bio/merqury/wrapper.py
> +        shell("cat out.hapmers.blob.png > {snakemake.output.hapmers_png}")
Good point.

2022-09-19 14:02 UTC, johanneskoester commented on bio/merqury/test/Snakefile
> +        logs=directory("logs/haploid/"),
Or add that folder to the log directive.

2022-09-19 14:03 UTC, johanneskoester commented on bio/merqury/test/Snakefile
> +        "minimal"
Instead of shadow, I'd rather let the tool itself run in a temp dir as cwd. This way, the complexity is hidden from the user.

2022-09-20 09:17 UTC, fgvieira commented on bio/merqury/test/Snakefile
> +        logs=directory("logs/haploid/"),
But then cannot use `log_shell_fmt`, right?

2022-09-20 09:27 UTC, fgvieira commented on bio/merqury/test/Snakefile
> +        "minimal"
It got a bit messy, but it should work. :smile:

2022-10-30 10:51 UTC, johanneskoester commented on bio/merqury/test/Snakefile
> +        logs=directory("logs/haploid/"),
yes, atm that is true

2022-10-30 10:51 UTC, johanneskoester commented on bio/merqury/test/Snakefile
> +        logs=directory("logs/haploid/"),
but I think that is worth it.

2022-11-02 11:48 UTC, fgvieira commented on bio/merqury/test/Snakefile
> +        logs=directory("logs/haploid/"),
Ok, just pushed new changes.

2022-12-01 11:37 UTC, johanneskoester requested changes

2022-12-01 11:37 UTC, johanneskoester commented on bio/merqury/wrapper.py
> +            shell("mv {out_prefix}.{prefix}.spectra-cn.st.png {out}")
Sorry, another request, I just noticed this. This is all very similar code. I'd say just turn this into one or a few functions and call them in a loop over the file suffixes.

2023-02-13 11:09 UTC, fgvieira commented on bio/merqury/wrapper.py
> +            shell("mv {out_prefix}.{prefix}.spectra-cn.st.png {out}")
Done

2023-03-22 07:34 UTC, johanneskoester approved these changes

2023-03-22 07:34 UTC, merged