feat: Wrapper and meta-wrapper for rbt consensus reads
snakemake/snakemake-wrappers pull request #544
Opened 2022-08-18 10:14 UTC by FelixMoelder

### Description

This adds two wrappers.
First a wrapper for rust-bio-tools consensus read calculation and second a meta wrapper which adds best practice post processing steps for consensus read calculation.

### QC

* [x] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

2022-08-23 07:28 UTC, johanneskoester requested changes

2022-08-23 07:28 UTC, johanneskoester commented on meta/bio/rbt_calc_consensus/meta.yaml
> +    Performs consensus read calculation on a marked bam records and merges single,
```suggestion
    Performs consensus read calculation on a marked bam and merges single, 
```

2022-08-23 07:28 UTC, johanneskoester commented on meta/bio/rbt_calc_consensus/test/common.smk
> +def get_processed_consensus_input(wildcards):
Please put this into the main Snakefile. People have to see the entire meta-wrapper code, so that they case decide how to use it (copy-paste or as a module).

2022-08-23 07:28 UTC, johanneskoester commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        "results/consensus/{sample}.merged.bam",
```suggestion
        "results/consensus/{sample}.bam",
```

2022-08-23 07:28 UTC, johanneskoester commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        "results/consensus/{sample}.merged.bam",
Is this a sorted bam then? That would be ideal. Maybe mention this as a comment, so that people don't have to wonder about it.

2022-08-23 07:28 UTC, johanneskoester commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        "master/bio/bwa/index"
```suggestion
```

Remove the index and consider it to be given. When people include this in their workflow, they will already have one because they have already generated a bam.

2022-08-23 07:28 UTC, johanneskoester commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        "results/consensus/sampleA.merged.bam",  # [hide]
```suggestion
```

Should also be removed. meta-wrappers should not be used standalone but inside of a larger workflow.

2022-08-23 07:28 UTC, johanneskoester commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        extra="--verbose-read-names",
Maybe add a comment with an explanation.

2022-08-23 07:29 UTC, FelixMoelder commented on meta/bio/rbt_calc_consensus/test/common.smk
> +def get_processed_consensus_input(wildcards):
I did so, but in that case the linting test failed.

2022-08-23 08:14 UTC, FelixMoelder commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        "results/consensus/{sample}.merged.bam",
Yes, I added this in the description of the meta-wrapper.

2022-08-23 09:01 UTC, FelixMoelder commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        "results/consensus/{sample}.merged.bam",
Removing the `.merged` suffix lets snakemake run endless as the `{sample}` wildcard would be valid for most of the other rules.
An option would be to exclude a `.` in the wildcard_constraints but this could cause issues if the wrapper is added to a workflow where a `.` is part of a later rule.

2022-08-29 11:36 UTC, johanneskoester requested changes

2022-08-29 12:15 UTC, FelixMoelder commented on meta/bio/rbt_calc_consensus/test/Snakefile
> +        "master/bio/samtools/sort"
I changed it to a fixed directory and set an appropriate rule name.
Previously, that rule was used two times. First ensuring that the initial input of the workflow gets sorted and another time later within the workflow of meta wrapper.
Now, I changed the wrapper in a way that the initial bam file is expected to be presorted as an unsorted bam-file would require the sorting rule to be generic.

2022-08-29 16:06 UTC, johanneskoester approved these changes

2022-08-29 16:06 UTC, merged